### ISSUE TITLE
Liege of the Primordial counts only one golem.

### ISSUE THREAD

**Issue by Djovis** [PathOfBuildingCommunity/PathOfBuilding#1028]
Liege of the Primordial, notable ascendancy passive skill of the Elementalist, must give 20% increased damage per summoned golem, but when calculating damage, it is always considered as if only one golem was called up.

**Comment by SaloEater** [comment]
I assume this passive is fine: when I add "The Anima Stone" gem, it gives some dps.

**Comment by Djovis** [comment]
So the problem is something else. I activate Liege of the Primordial and Golem Commander passives, each one adds +1 to maximum number of golems, but dps increases only for the first golem on skills panel, adding new ones does not have any effect on it.

**Comment by Djovis** [comment]
> I assume this passive is fine: when I add "The Anima Stone" gem, it gives some dps.

So the problem is something else. I activate Liege of the Primordial and Golem Commander passives, each one adds +1 to maximum number of golems, but dps increases only for the first golem on skills panel, adding new ones does not have any effect on it.

**Comment by LocalIdentity** [comment]
Once you have a golem skill in your build, Elemancer and Liege of the Primordial assume you to have your max number of summoned golems. Which is why you get the DPS increase when adding the 1st golem gem. Also, if you ever think something is not working, make sure you check the calcs tab cause in there is shows the increased damage that liege gives you
