### ISSUE TITLE
When using the new "power per point" it suggests anoint only nodes

### ISSUE THREAD

**Issue by numbers-pwn** [PathOfBuildingCommunity/PathOfBuilding#1226]
* **What happened?**
PoB will only suggest "Tenacity" on my particular tree when I select both "power per point" and "show top node". I imagine the anoint only nodes are considered to be 
* **What were you trying to do?**
Use the new feature to figure out which tree nodes were the most efficient.
* **What steps will reproduce the bug?**
Use the feature, have the most valuable per single point node be annoint only.
* **Does it reproduce every time? If not, why so?**
Yes
* **Additional information:**
Classes/CalcsTab.lua 
  local pathCost = node.path and #node.path or 1

This should weight extremely expensively, instead of being treated as a 1 length path, or be handled in a separate checkbox
https://imgur.com/wHcZdfj

**Comment by imatimba** [comment]
An option to disable keystone suggestion also would be nice, my LL character with 6 auras is suggested to take Supreme Ego because it only calculates the 50% more Effect and not that I would lose 5 auras.

**Comment by Wires77** [comment]
Since anointable nodes can be handled in a separate UI in the items tab, I'm planning to remove anoints from consideration entirely.

Keystones I'm planning on leaving in right now, that issue sounds more to do with Supreme Ego.  I am going to add another UI popup that will list the nodes, and that will be more customizable.
