### ISSUE TITLE
Attack speed not calculated correctly? its lowering dps

### ISSUE THREAD

**Issue by terbenstaar** [PathOfBuildingCommunity/PathOfBuilding#1237]
![Path_of_Building_T8004KxjOk](https://user-images.githubusercontent.com/39078335/87863832-8a29d300-c968-11ea-9221-91054f8fb2df.png)

Left weapon is my current. To right one i increased attack speed and now its giving lower dps.
Version 1.4.170.5

**Comment by Regisle** [comment]
No Pastebin makes it a little hard to determine issue, its likely due to using new warcries/slams
![image](https://user-images.githubusercontent.com/49933620/87867134-02c07c00-c9c9-11ea-8f24-f66623ee4a00.png)
Though as to why total dps goes down I am unsure, maybe unlucky with breakpoints?
(note these will be easier to see whats happening when https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/1212 gets merged)

If this isnt the issue (or preferably give the pastebin anyway incase theres another issue) the pastebin would be useful to debug the issue

**Comment by terbenstaar** [comment]
hi.
sorry, completely forgot this post. tested high attack speed weapon with 1.4.170.7 patch and it seems to be fixed. damage is increasing with higher attack speed.

**Comment by LocalIdentity** [comment]
Good to hear that it's fixed
