### ISSUE TITLE
Attack rate 30.00

### ISSUE THREAD

**Issue by flash1205** [PathOfBuildingCommunity/PathOfBuilding#1266]
https://pastebin.com/Kip4L0cK

In this build, attack rate is 30.00 excess.
But attack rate is not show more than 30.00.

Can you fix it?

**Comment by Lothrik** [comment]
This is intentional, not a bug.

You can't attack faster than once per server tick (apparently -- I don't know how this was verified): https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/816

**Comment by whyismyapscapped** [comment]
I would disagree with the attack rate cap being a thing. Please fix it is ruining my builds by making their dps suffer in the high teens of teh billions instead of rightfully in the low 20 billions. 
![image](https://user-images.githubusercontent.com/72285739/94980180-e377bc00-04ec-11eb-8e50-4b1ce52b04fe.png)
and I made a highlight going of having more than 30 aps with : https://www.twitch.tv/videos/758975392
