### ISSUE TITLE
How to add spectre to the library?

### ISSUE THREAD

**Issue by Gameplayraja** [PathOfBuildingCommunity/PathOfBuilding#1291]
I am trying to add the new monster from harvest to the library myself and i don't seem to be able to find the Spectre Tree anywhere. How would one go about this?

I am trying to add the Primal Blisterlord to the tree.

**Comment by Dodgy-J** [comment]
Not sure what you mean exactly, you dont add spectres to the tree, 

If you mean add them to the library you need to either follow the steps I outlined in a reddit post https://www.reddit.com/r/pathofexile/comments/hoip63/guide_to_manually_adding_spectres_to_pob/ 
however since my post PoEDB now has a lot of the work done for you, so using the data it proves and correcting any errors should be sufficient.
or
follow the steps covered (this one is more programatic)
https://www.pathofexile.com/forum/view-thread/2181275/page/1132#p23256026
and https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CONTRIBUTING.md#exporting-data-from-a-ggpk-file
