### ISSUE TITLE
Add claw crit chance/multi to Law of the Wild's minions 

### ISSUE THREAD

**Issue by Dodgy-J** [PathOfBuildingCommunity/PathOfBuilding#1312]
The wolves have:
Modifiers to Claw Critical Strike Chance also apply to Minions
Modifiers to Claw Critical Strike Multiplier also apply to Minions

PoB already has the wolves as having the flags:
modifiers_to_claw_critical_strike_chance_apply_minion_critical_strike_chance
modifiers_to_claw_critical_strike_multiplier_apply_minion_critical_strike_multiplier

But that flag isnt coded in at all, so it has no effect.

my attempt at doing it is attached, but it modifies files we arent supposed to, so not willing to make a pull request with my solution.
[Add Law of the wilds minion crit.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5051524/Add.Law.of.the.wilds.minion.crit.txt)

**Comment by ppoelzl** [comment]
> but it modifies files we arent supposed to

The mod cache is automatically generated by holding `Ctrl` during startup when you run the application in dev mode. For more information, please refer to [CONTRIBUTING](../blob/master/CONTRIBUTING.md).

I would like to point out that it is completely fine to submit your work as a PR even if it is not final. For that, I recommend that you label your PR as WIP and specifically ask for feedback on anything you are not sure about. Plus it is much easier for maintainers to have something to `git checkout` instead of having to piece it together from your attached text file.

**Comment by LocalIdentity** [comment]
Fixed
