### ISSUE TITLE
Implicit corrupted Skillgem reserved by Life and not Mana

### ISSUE THREAD

**Issue by jix91** [PathOfBuildingCommunity/PathOfBuilding#1339]
Prism Guardian corruption Determination / Grace / Discipline Lvl 23 is reserved with Life, when it in Reality is reserved by Mana. It is **NOT a Socketed Gem.**

**Comment by holyzeus** [comment]
Can confirm.

Some more info:
When Importing a character with such an item, the Determination / Grace / Discipline skills gets automatically added and activated in your Skills list. At this point, it correctly reserves mana. If you now save your build, go back to your Builds list and then select the build with the Determination / Grace / Discipline, it starts reserving life instead of mana.

**Comment by Irfy** [comment]
Additional info: *None* of the Prism Guardian aura modifiers apply to the corruption aura. So, neither does a corruption aura have Blood Magic, nor does it have 25% reduced mana reserved, nor does it have +2 to its level. It all has to do with the repeatedly used wording "Socketed [Aura] Gems" simply not applying to the corruption aura.

A workaround is to disable the corruption aura and recreate it manually as an independent group with level 23 and 0 quality -- this will correctly reserve mana, without any of the Prism Guardian mods, as intended.

**Comment by Wires77** [comment]
When testing with a shield like this in an otherwise empty build, I can confirm that upon loading the corrupted implicit aura reserves life.  Re-equipping the shield, however, properly resets the aura to reserve mana, so the issue is in the importer for sure.
