### ISSUE TITLE
Blade Blast's blade count is ignored when supported by spellslinger

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [PathOfBuildingCommunity/PathOfBuilding#1343]
**Is your feature request related to a problem? Please describe.**
You can't see how big of a hit you would be doing with different amounts of blades like you can when not supported by spellslinger.

**Describe the solution you'd like**
Total Dps (which doesn't work at all with spellslinger + blade blast) could use the cooldown to estimate actual dps. 

**Describe alternatives you've considered**
Alternatively a much easier, less helpful (but still much improved) option would be to have a line multiplying avg hit by # of blades

**Comment by Quotae** [comment]
Trigger methods which require the player to hit the enemy or use a skill, like Spellslinger and Cast on Critical Strike, likely won't ever be given a DPS output. We don't like to list any numbers that we can't be absolutely sure about, and with those kinds of triggers there's no way to know how close the player will actually be to triggering it "perfectly" on the cooldown. We don't want to mislead users with a DPS number that's inaccurate to real-world performance.

Cast While Channeling is an example where we would (and did) use the cooldown as the hit rate, because CwC skills will always trigger on the cooldown perfectly as long as you're holding the button. There's no variance to it.

Blast Blast itself has its own issues, too. When you're self-casting it, the skill assumes that you're hitting with your set number of blades every single time you cast it, which is basically never right. There should be a fix for that in the next update, but that's not really the point of this issue.
