### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by cschneid** [PathOfBuildingCommunity/PathOfBuilding#1370]
With Path of Exile getting an official Mac client, it'd be nice to be able to run Path of Building on OSX as well. 

What would it take to get a lua app running? It looks like the SimpleGraphic library is (perhaps) windows specific? Any other major components?

**Comment by ppoelzl** [comment]
PoB should run fine in WINE. The non-portable components are the Lua host and SimpleGraphic.

**Comment by cschneid** [comment]
I'm a programmer, but inexperienced with Lua - is there a link to the Lua Host -- OSX has a Lua interpreter, so perhaps something can be substituted. 

And SimpleGraphic looks reasonably well architected to support other backends perhaps?

**Comment by cschneid** [comment]
And yes, WINE is probably the easiest answer. But native is always a little better when possible. 

Thank you for the very quick reply!

**Comment by ppoelzl** [comment]
There is also https://github.com/philroberts/pobfrontend. However, recently we started on our own independent development on SimpleGraphic, so this might become outdated in the future. PathOfBuildingCommunity maintains https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic instead. Please note that we haven't merged any of the work on it yet, due to time constraints. 
Both `SimpleGraphic.dll` and `Path of Building.exe` are not open source and this forked project does not have access to their source code. For SimpleGraphic at least though, we were able to obtain the source of an earlier version. https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic is based on that source.

**Comment by larsjoakimgrahn** [comment]
Since Catalina MacOS no longer supports running 32-bit programs, wine no longer works. If it possible to build a 64-bit executable that would pretty much mean there is no need for a separate MacOS version. 

As it stands, it's not very easy to get PoB running on MacOS.

**Comment by ppoelzl** [comment]
@larsjoakimgrahn As I stated in the comment above, we do not have access to the source code of the executable. So no, we won't be able to build a 64-bit executable.

**Comment by Wires77** [comment]
@larsjoakimgrahn While not an officially supported site, https://poe.party is an online version of PoB made by the same guy that does poe.trade.  It might work for you if you can't get the desktop version working

**Comment by CaramelHeaven** [comment]
If anyone wants to build from zero on mac os this app natively with a prettier interface, just call me c:

**Comment by hsource** [comment]
Here's a link to a forum thread for the [Mac version of Path of Building](https://www.pathofexile.com/forum/view-thread/3009944). I included instructions on how to update the POB version too!

**Comment by WolfInABarrel** [comment]
Not that I want to resurrect a dead thread, but I was able to convert PathOfBuilding to an Universal Mac App using Xcode, so the code seems clean enough for MacOS tools to just compile it for you. I can provide the binary for upload if there's any interest still.

**Comment by WolfInABarrel** [comment]
> Not that I want to resurrect a dead thread, but I was able to convert PathOfBuilding to an Universal Mac App using Xcode, so the code seems clean enough for MacOS tools to just compile it for you. I can provide the binary for upload if there's any interest still.

Done, it's accessible as a commit under my own forked version, if anyones interested.
