### ISSUE TITLE
Merge PRs to a nightly dev branch

### ISSUE THREAD

**Issue by davoodinator** [PathOfBuildingCommunity/PathOfBuilding#1373]
start accepting+closing pull requests into a nightly branch and this will let people test and find bugs earlier than in a mad rush in the week(s) preceding and following a new league.

**Comment by Regisle** [comment]
I mean the dev branch is normally pretty far ahead of the main branch, if you want the stuff earlier, but yeah

**Comment by mitant** [comment]
@Regisle I don't believe that's the point being made.  It sounds to me like the ask is for the open PRs to be merged so that they can be reviewed/tested at a faster/iterative pace in a new nightly branch as opposed to all at once.  

These PRs have not made it to any branch, not even dev, so basing your copy of POB off of dev does not solve anything related to open PRs.

**Comment by davoodinator** [comment]
yeah what he said

basically what im seeing atm is

PR -> master or dev

it should be  

pr -> dev (nightly) -> master (at various stages when dev is stable)

**Comment by ppoelzl** [comment]
We will merge PRs to dev more frequently from now on.
