### ISSUE TITLE
Skills 'Enabled' checkbox hover stats missing

### ISSUE THREAD

**Issue by syd-h** [PathOfBuildingCommunity/PathOfBuilding#1427]
When enabling/disabling support gems to a skill there is no hover box with stats like in the main PoB. No approximate added damage or mana cost at the selected gem levels.

https://i.imgur.com/gMCrjud.png

Release 1.4.170.8

**Comment by Quotae** [comment]
Can you share a Pastebin for your build? I'm definitely seeing the box show up.

![image](https://user-images.githubusercontent.com/39030429/94378191-15ec7800-00ed-11eb-877c-faac2c6a53df.png)

**Comment by syd-h** [comment]
That was on release 1.4.170.8(forgot to add). Since have updated to 1.4.170.12.. I see some of the hover boxes but not for every gem. 

Well I might have figured something out? It seems the hover box is only showing when the left side quick stats has that specific skill selected. Skills like Aura's show the tooltip regardless.

Below is the same skill setup in the skills section. Then one with and without that skill group selected on the quick stats side.

![dIACM17 1](https://user-images.githubusercontent.com/25559485/94402166-ab155e00-0139-11eb-89ae-36ddf586329d.png)
![Y0Em88K 1](https://user-images.githubusercontent.com/25559485/94402183-afda1200-0139-11eb-9c08-81e172e26a36.png)

**Comment by Wires77** [comment]
This is because Bladefall has no effect on any of your stats when Blade Blast is your main skill.  The reason you see the box when hovering over auras is because they (at the very least) change your mana reservation.

**Comment by syd-h** [comment]
Even still if I hover on any of the supports it's the same thing. Only the current non-Aura skill selected on both sides shows support stats. I just happened to hover over the main skill in that example.

**Comment by Wires77** [comment]
Yes, because none of those supports do anything for Blade Blast, either.  Any gem you hover over or select only displays changes to your currently selected main skill (the one on the left).  This is by design, so you can augment supplementary skills with different supports to see how it affects your main skill's damage (think Combustion Support on a flame totem, while your main skill is a fire spell)

**Comment by syd-h** [comment]
Going back to my first port as to why I noticed it. In the original PoB I recall you could always see the tooltips regardless of what was selected on the left side.

Regardless wouldn't it be easier to have to the tooltips always show adjustments without having to select something twice?

**Comment by Wires77** [comment]
I checked out an old version of PoB and was unable to see the behavior you're describing.  Unfortunately I don't think it ever worked that way.

PoB is based around the assumption that you're only calculating damage for one skill.  It's not that we're hiding the tooltip when your main skill isn't selected, it's that the checkbox does nothing for your main skill, so there is nothing to show.  What you're asking for is a combined DPS report of multiple skills instead of just one main skill.  While that's potentially possible, it will have to be a new feature, not a bugfix.
