### ISSUE TITLE
Dmg per Poison on Calcs tab mismatches left sidebar Total Damage per Poison

### ISSUE THREAD

**Issue by Xeverous** [PathOfBuildingCommunity/PathOfBuilding#1446]
https://pastebin.com/cP6a6ELq

In this build, on the Calcs tab the "Poison DPS" value is way too low. It does not factor support gems into "Total More" (Unbound Ailments, Deadly Ailments, Swift Affliction). The calcs "Dmg. per Poison" is way lower than the value of "Total damage per Poison" on the left sidebar.

https://pastebin.com/VEBFyZSN

In this build (which has better gear) these 3 supports are replaced with their Awakened versions. "Total More" is way higher than in the first build. The calcs "Dmg. per Poison" matches with the value of "Total damage per Poison" on the left sidebar.

**Comment by Quotae** [comment]
Looks good to me on 1.4.170.12:
![image](https://user-images.githubusercontent.com/39030429/94378468-84cad080-00ef-11eb-8918-017a341321eb.png)

I don't think this was fixed in this patch, so it's possible you were looking at the wrong version of Toxic Rain (I made that mistake when I first loaded the build). Also, the second build's bow has a mod which gives 60% more poison damage, which makes that number much bigger. Here's what the first build looks like if you just throw on the second build's bow with no other changes:

![image](https://user-images.githubusercontent.com/39030429/94378535-f99e0a80-00ef-11eb-8300-b4852b02e63c.png)

Making a couple of other changes (extra frenzy charge, same awakened supports) brings this number to the same as the second build.
