### ISSUE TITLE
Very long mod lines are skipped

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#152]
Very long mod lines such as Fortress Covenant's "Notable Passive Skills in Radius are Transformed to instead grant: Minions take 20% increased Damage" are skipped in the unique item DB and won't show up on items in PoB's unique item list tooltips.

**Comment by pHiney** [comment]
Where is it being lost ?

This image was the item list.
but adding it to the build and using it shows the tool tip also. Have i misunderstood ?

![image](https://user-images.githubusercontent.com/4302241/74140597-7657a380-4c49-11ea-9449-51644a94a5c2.png)

version was the live 1.4.157.3 (not a dev build)

**Comment by LocalIdentity** [comment]
The a notable passive skills line and minions takes line are meant to be q line of text, but at the moment they’re spill into 2 lines. Same thing with inspired learning if you take a look

**Comment by ppoelzl** [comment]
Quickening Covenant is another offender

**Comment by pHiney** [comment]
1.
Where does the information for jewels.lua comes from ?
for Quickening Covenant; If you change the colon in "Notable Passive Skills in Radius are Transformed to instead grant: Minions have 25% reduced Movement Speed" to a comma, the line displays.

This will probably be the code that looks for entries like "Requires Level: 20" and "Limited to: 1" (Probably ParseRaw in Item.lua)

So can jewels.lua be updated that way or will it be overwritten next league ?

2.
#1 doesn't explain the failure of "Inspired Learning". It has a different issue. Adding a line of text to the jewel (in jewel.lua) makes the missing line appear 
![image](https://user-images.githubusercontent.com/4302241/74333316-ccfce300-4deb-11ea-8f1e-d2aa0af0bc3b.png)
Why is the last line red ? Is that because it doesn't appear somewhere else in the PoB ?

3.
The cutoff seen in my screenshot above of "Fortress Covenant Cobalt Jewel" can be solved by commenting out line 277 of ItemsTab.lua "-- self.displayItemTooltip.maxWidth = 458". 
This will remove the artificial limit and cause the line to be on one line.
*HOWEVER*, the increased size of the tooltip is not recognized by the horizontal scrollbar.
I don't understand how the scroll bar knows what the right most control is. Perhaps if we put the tooltip in a hidden box that sizes itself around the tooltip.

**Comment by ppoelzl** [comment]
1.) Unique item data is not in the GGPK anymore, so all uniques have to be added manually. As you can tell, this can be quite error-prone at times, with many uniques still left with outdated or incorrect data.
(I assume you refer to `/Data/Uniques/jewel.lua`, not `/Data/3_0/Bases/jewel.lua`, which is generated by the exporter)

2.) PoB will skip all unsupported mods on items until in encounters a supported mod. After that, unsupported mods will also be displayed. I'm not sure which part of the code is responisble for that, but a currently used band-aid fix is to add a line `Implicits: 0` before the first mod.
Mods are translated by `/Modules/ModParser-3_0.lua` and subsequently added to `/Data/3_0/ModCache.lua`. All mods that are not present in this mod cache will appear red.

3.) The bug doesn't seem to only be graphical. Overly long mod lines just disappear at some point.

**Comment by ppoelzl** [comment]
Also I want to add that there is at least one other mod with a colon that works just fine:
Coated Sharpnel's "Passive Skills in Radius also grant: Traps and Mines deal (2-3) to (4-6) added Physical Damage".

**Comment by optionsreaper** [comment]
This may also be fixed by PR [#240](https://github.com/LocalIdentity/PathOfBuilding/pull/240)

**Comment by ppoelzl** [comment]
Fixed in 1.4.158.1
