### ISSUE TITLE
Problem with starting Path of building

### ISSUE THREAD

**Issue by Ruggig** [PathOfBuildingCommunity/PathOfBuilding#1595]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`
i downloaded the latest one from youre site, 1.4.170.12
Please try to fill in as much of the template below as you're able.

* **What happened?** When iam starting pathofbuilding.exe, it instead launches cmd.exe (windows command processor) which says "press any key"
* **What were you trying to do?** start up POB
* **What steps will reproduce the bug?** everytime i startup
* **Does it reproduce every time? If not, why so?**Yes
* **Additional information:** I have unninstalled multiple times, cause first i have problems inporting builds, cause i got error messages something like, "error on frame" and a bunch of numbers.

If you receive an error or experience graphical bugs, include a screenshot.
![Skärmklipp](https://user-images.githubusercontent.com/72304017/94991269-46676280-0582-11eb-9cdd-82e66d17b63f.PNG)

Also include a shareable build link, even in cases where you experience issues not specific to a certain build. This helps us greatly to reproduce bugs faster.
at this time, i cant even start the program.

**Comment by coldino** [comment]
PoB must be launched via its installed shortcut, not the exe directly

This is unfortunate, but it comes from being reliant on the original OpenArl exe.

**Comment by ppoelzl** [comment]
While the workaround @coldino suggested should fix this issue, the root cause was me accidentially building the 1.4.170.12 release with an outdated toolchain.

I've since published a new 1.4.170.14 release that should properly fix this issue and allow you to run PoB without shortcut. Additionally, I've added guards to our internal infrastructure that should prevent us from publishing with an outdated toolchain again.

Thank you for reporting this bug and sorry for the inconvenience!

**Comment by Ruggig** [comment]
Okey, so i should unninstall. And download it again ?

**Comment by ppoelzl** [comment]
Yes, download the latest release, 1.4.170.14.

**Comment by Ruggig** [comment]
Okey, seems to be working now.. After ive installed the new release, thanks for the help, and a great program !
