### ISSUE TITLE
Infernal Blow debuff damage

### ISSUE THREAD

**Issue by Bryserker** [PathOfBuildingCommunity/PathOfBuilding#1640]
**Is your feature request related to a problem? Please describe.**
Not a problem, just trying to figure infernal blow out. I get the impression the debuff is not calculated as part of the DPS. 

**Describe the solution you'd like**
It would be nice to see the additional single target DPS when exploding 6 debuffs on a stronger enemy.

**Describe alternatives you've considered**
Currently in my theorycraft i'm doing: (avg dmg * attack rate) * 1.66 (each debuff deals an additional 66% damage on explosion). However I'm unsure wether or not it's calculated already and the DPS of infernal blow is just.. that bad.

**Additional context**

**Comment by Quotae** [comment]
Infernal Blow is getting some support in the next update. However the debuff damage will be a separate skill part, so it's not quite as convenient as you wanted. The reason is because the explosion damage is considered area damage and is affected by area damage modifiers, but the melee part isn't. And because of how PoB works, there's no easy way to make modifiers only apply to part of a skill's damage, so it has to be split up.

**Comment by Bryserker** [comment]
Thanks for the reply! Great to hear and that's perfectly convenient as far as I'm concerned.

**Comment by ppoelzl** [comment]
Added in 1.4.170.15.
