### ISSUE TITLE
Infernal Cry Covered in Ash Effect

### ISSUE THREAD

**Issue by Lothrik** [PathOfBuildingCommunity/PathOfBuilding#1644]
Infernal Cry is supposed to provide a fixed Covered in Ash effect based on Warcry Power:
"Covers Enemies in Ash, causing 3% increased Fire Damage taken per 5 Power, up to 20%"

This does not scale with gem levels. Yet in Path of Building currently, it does.

With 20 Warcry Power, checking the Covered in Ash effect applied by Infernal Cry:
* At Gem Level 1: 7.5% increased Fire Damage Taken
* At Gem Level 10: 8.1% increased Fire Damage Taken
* At Gem Level 21: 9% increased Fire Damage Taken

Additionally, *all* of these values are wrong. 20 Warcry Power should grant 12% increased Fire Damage Taken.

**Comment by Regisle** [comment]
This is likely because the warcry calculation mode is set to average, and level increases its duration and speed, supporting it with increased duration gives the correct 12%, though there seems to be an issue with setting warcry calculation mode to maximum in that it doesnt also set it to the correct 12%
