### ISSUE TITLE
Divergent Determination not correctly converting evasion to armor.

### ISSUE THREAD

**Issue by dsholland08** [PathOfBuildingCommunity/PathOfBuilding#1701]
Divergent Determination is not operating properly in regards to the alternate quality.
I have 20k Evasion but still only 600 armor. When switching from divergent to anomalous, there is no change whatsoever. 
I currently have this linked with an enlighten level 4, divergent purity of ice, and divergent purity of elements. 

Thank you for your time and effort.

https://pastebin.com/maRJuPH5

**Comment by Dodgy-J** [comment]
I had to edit files that say "-- This file is automatically generated, do not edit!" to get it to work so im not willing to make a pull request, but I think I've got it somewhat working (unsure if the end calculations are correct)

in act_str.lua in Determination's StatMap 
["evasion_rating_%_to_add_as_armour"] = {
			mod("EvasionGainAsArmour", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Aura" }),
		},

And then in CalcDefence-3_0.lua (i put it under convLifeToArmour, as its essentially an altered copy/paste) 
local convEvasionToArmour = modDB:Sum("BASE", nil, "EvasionGainAsArmour")
		if convEvasionToArmour > 0 then
			armourBase = modDB:Sum("BASE", nil, "Evasion") * convEvasionToArmour / 100
			local total = armourBase * calcLib.mod(modDB, nil, "Evasion", "Armour", "ArmourAndEvasion", "Defences")
			armour = armour + total
			if breakdown then
				breakdown.slot("Conversion", "Evasion to Armour", nil, armourBase, total, "Armour", "ArmourAndEvasion", "Defences", "Evasion")
			end
		end

**Comment by Regisle** [comment]
@Dodgy-J a few things to note if you do a pull request, act_str.lua is generated from act_str.txt in /Export/Skills/ edit it there and run export to see if it generated correctly (or just throw a PR up and someone reviewing it will run export, but act_str.txt must be edited), also "convEvasionToArmour " is an incorrect name as its not a proper conversion (but it should be fine to keep as explained below)

 that begin said it probably also needs to be moved (to work correctly) and Iron reflexes should also be moved over to the new system (as conversion instead of gained as)

**Comment by Sticky-Bits** [comment]
There's been a huge amount of discussion on this topic on reddit since the last comment here, you guys might find it useful if you weren't aware. There's also a bunch of comments from Mark from GGG explaining mechanics and calculations.

https://www.reddit.com/r/pathofexile/comments/jsh2vf/12_billion_armour_project_results_math_story/

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
