### ISSUE TITLE
Beacon of Madness

### ISSUE THREAD

**Issue by Hedgeg** [PathOfBuildingCommunity/PathOfBuilding#1728]
1.4.170.16 fork build
* "All Damage inflicts Poison while affected by Glorious Madness" stat doesnt work
* also not every version of this boots presented

Poison doesnt calculate at all:
*it only occurred for extra damage from Atziri's promise

![Screenshot_998](https://user-images.githubusercontent.com/74453689/99146414-01f2da80-2689-11eb-95cd-80dfd229999b.png)
![Screenshot_1](https://user-images.githubusercontent.com/74453689/99146416-061ef800-2689-11eb-8cd5-e27850c06bf2.png)
![Screenshot_2](https://user-images.githubusercontent.com/74453689/99146417-07502500-2689-11eb-841f-e9d23462527f.png)
![Screenshot_3](https://user-images.githubusercontent.com/74453689/99146418-08815200-2689-11eb-87c4-d0979cbbaa9d.png)

**Comment by Wires77** [comment]
In general, mods that appear in red text are currently unsupported in PoB ("All Damage inflicts Poison while affected by Glorious Madness" appears in red).

Looks like we do have an issue with how same-named uniques with different base types are stored in the unique DB, though, so that can be fixed as an issue for sure.  The other mod line is going to have to be a new feature request, though.

**Comment by ppoelzl** [comment]
@Hedgeg Please fill out the bug report template to report bugs.

**Comment by ppoelzl** [comment]
Fixed the item bases issue in release 1.4.170.19. Eventually, support for their unique effects might be added at a later point in time.
