### ISSUE TITLE
Allow sorting calculations when out of focus

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#1746]
Currently, when the program is out of focus, it pauses all activity, including all sorting calculations in the Items or Tree tabs. Because they tend to take some time, you have to wait them out doing nothing. Previously you could simply do something outside of Path of Building, now you can't.

Please, allow the calculations to proceed when out of focus.

**Comment by ppoelzl** [comment]
Pausing the program when it's in the background is desired behaviour. Otherwise, Path of Building would continue to use up processing power while out of focus. The behaviour you're experiencing is a direct result of us reducing Path of Building's impact on overall PC performance, as this has been requested numerous times.

**Comment by ZzZombo** [comment]
Please reconsider this. As the user who opened the issue that ultimately have led to the current behavior, I'm well aware of that. I concur it's one thing to perform superfluous updates to the UI and whatnot due to reacting to mouse events and whatnot when in background – that you guys rather wonderfully managed to solve – and thus straining the CPU with meaningless work, and another to load it with calculations I *actively* invoked. You can still freeze the UI and everything not actively needed for such calculations and keep the benefits of the optimizations made when not in foreground. I vote to keep this issue opened until this is implemented.
