### ISSUE TITLE
Increased curse effect corrupted implicit stacks with regular curse

### ISSUE THREAD

**Issue by Ydoum** [PathOfBuildingCommunity/PathOfBuilding#1774]
Setup used:
Gloves with **Curse Enemies with Despair on Hit, with 48% increased Effect**
Hextouch + level 20 Despair

Scenario:
1. Damage with only Hextouch Despair: 1.5mil
2. Damage with Hextouch Despair + corrupted gloves implicit that applies a separate despair: 1.7mil

I don't think these should stack, considering they are different sources of Despair curse. It definitely appears like the inc. effect is applying to the lvl 20 Despair from Hextouch - should it? Correct me if I am wrong here, but the curse with higher effectiveness should cancel out the weaker curse.

![image](https://user-images.githubusercontent.com/47370800/100595327-0eb73580-32fb-11eb-85de-5c5d1fb6c620.png)

**Comment by DavidStrid** [comment]
Could you add the build code for the setup you had when you encountered this issue? 

Also for clarity until then, is the despair and hextouch gems socketed in the gloves?

**Comment by Ydoum** [comment]
> 
> 
> Could you add the build code for the setup you had when you encountered this issue?
> 
> Also for clarity until then, is the despair and hextouch gems socketed in the gloves?

PoB: https://pastebin.com/NieAqyH7

Hextouch is in Hidden Blade; Despair hence is triggered by Unseen Strike

Note when switching gloves to Hands of the High Templar with the despair curse on hit with inc. effect, the damage goes up massively. Removing the line of the corrupted despair implicit reduces the displayed damage.

**Comment by DavidStrid** [comment]
After experimenting with your build code and trying the same for setup + blasphemy and self cast setups,  I can confirm that this problem exists for all curses and is easily reproducible.

Any of the "Curse enemies with x on Hit, with #% increased effect" corruptions are globally increasing the effectiveness of said curse, instead of only affecting the locally applied curse. E.g. All curses of the same name will receive the increased effect.

If any coder wants more information let me know and I can share a pob code with further examples.

**Comment by LocalIdentity** [comment]
These mods no longer exist so I'm closing this issue
