### ISSUE TITLE
Barrage Support Calculation in reference to Shrapnel Ballista

### ISSUE THREAD

**Issue by gforce215** [PathOfBuildingCommunity/PathOfBuilding#1847]
The calculated dps vs actual in game dps is very off. I tested in multiple maps on multiple map bosses without mods..plain white maps. The reduction in damage on the gem in practice really cripples the damage of the build.  It looks like skill hit damage goes way up in the calc screen....when in game the skill hit damage goes down over 10x. When replaced with Brutality in game everything melts. I don't know where there issue is in the calculation, but something isn't quite right.

**Comment by Regisle** [comment]
pastebin?

**Comment by gforce215** [comment]
Oops sorry, here ya go
with barrage
[](https://pastebin.com/W0yMuNtM)
with brutality
[](https://pastebin.com/fDBWQz1K)

![brutality](https://user-images.githubusercontent.com/9442313/104330797-5b765a80-54bc-11eb-8a4a-1e55b71f020e.PNG)
![barrage](https://user-images.githubusercontent.com/9442313/104330804-5d401e00-54bc-11eb-86f8-c3d620e29e83.PNG)

**Comment by QuickStick123** [comment]
This is interesting and likely because ingame this skill can shotgun. https://www.poewiki.net/wiki/Shrapnel_Ballista This means you might have x4 damage then in PoB when using the Brutality setup. This is not the case when using barrage support as in PoB we assume all projectiles hit resulting in a similarly displayed damage number in PoB but significantly less damage ingame.
![image](https://user-images.githubusercontent.com/31533893/221745542-ac1d24c6-0417-44e8-bf07-8dfd28fb15d9.png)
![image](https://user-images.githubusercontent.com/31533893/221745551-ee0e3aae-1cd4-4f0e-a967-2c99ec44c8ca.png)
