### ISSUE TITLE
Unit testing framework evaluation

### ISSUE THREAD

**Issue by Fish013** [PathOfBuildingCommunity/PathOfBuilding#186]
## Unit testing framework evaluation
Let's get started by evaluating how we want unit tests to look like and what framework should be used - if one.
### Frameworks
The most popular lua testing frameworks i found so far are:
- [busted](https://github.com/Olivine-Labs/busted)
- [luaunit](https://github.com/bluebird75/luaunit)

### Framework criteria
Part of the evaluation process is to define criteria important to usage as framework for testing PoB code.
I'll begin with some that come to my mind, please complement like you see fit:

- Ease of use: setting up the testing environment should be straight forward to get new contributors on board easily
- CI-capable: framework should be runnable from CI environment to setup a GitHub Actions pipeline
- Common test features for PoB: framework should provide basic features to compare shallow/deep tables and favorably provide other functionality beneficial to PoB testing 

### Testing setup
Test will likely be executed in two different environments. Locally on the developer machine and on GitHub Actions (tendentially inside a docker container with luajit)
We need to define how the different environments are setup and how test are being executed.

- Do we ship a luajit environment with the dev repository?
- Do we write a small wrapper that lets us execute tests locally via the "Path Of Building.exe" executable

### Testing structure
We have to define how we layout the folder and file structure for tests.

I could imagine something like that inside the root project folder:
```
/test/unit/ClassToTest.lua
/test/integration/ClassToTest.lua
/test/snapshot/SnapshotTest.lua (to be discussed seperatly)
```

### Test structure
Finally we need to define how the individual Tests look like.

### Conclusion

Please join the discussion so we can get started asap with prototyping.

**Comment by duraz0rz** [comment]
I have thoughts, based on my past experiences with unit testing in other languages (not Lua):

- Docker will probably be the easiest way to get a testing environment set up. [There's a Docker image for luajit](https://hub.docker.com/r/nickblah/luajit/) ready to use.
  - Since the Github Action runners have Docker on them, you can use a Docker volume mount to mount the code directory and run the tests the same way both locally and in CI: `docker exec -v <directory on VM>:<directory inside container> <command to run tests>`

- Both of those frameworks should do what you want. It should come down to what style people are comfortable with (RSpec/BDD style that `busted` provides, or a more traditional approach that `luatest` provides).

- Both `busted` and `luatest` support outputting test results in a way that is consumable by a CI system, it looks like.

**Comment by MindlessRuff** [comment]
Is anyone else working on this feature at the moment? I've setup a simple Dockerfile which utilizes the image suggested by @duraz0rz and installs luaunit via luarocks.

I'm having trouble finding a simple function to test for a proof of concept. I'm more familiar with Python and Java than lua. Could someone point me to good starting point?

**Comment by ppoelzl** [comment]
@MindlessRuff Try testing one of the functions in `Common.lua`. They are fairly self-contained.

**Comment by buddyp450** [comment]
@MindlessRuff did you make any progress? I'm about to tackle the same thing.

**Comment by ppoelzl** [comment]
Superseded by #2004
