### ISSUE TITLE
Slayer's Brutal Fervour doesn't apply the increased Maximum Recovery

### ISSUE THREAD

**Issue by Lulloser** [PathOfBuildingCommunity/PathOfBuilding#1869]
As the title says the Ascendancy node doesn't increase the Lifeleech stats.

https://pastebin.com/MvCeJC5t

**Comment by randomflyingtaco** [comment]
Brutal Fervour gives "100% increased Maximum Recovery per Life Leech" which extends the duration of individual life leech instances, but not the rate of life gained from life leech.  So the only way the stat would show up is if you couldn't hit the leech cap without the extra leech duration.
This should be closed because it is not a bug.
