### ISSUE TITLE
Liege of the Primordial

### ISSUE THREAD

**Issue by looqpool** [PathOfBuildingCommunity/PathOfBuilding#2002]
I am not sure if it's a bug or if I am doing something wrong with this PoB. When I allocate Liege of the Primordial for the new Elementalist tree, I do not get increased damage per summoned golem **PAST THE FIRST GOLEM** and I do not receive the effects of buffs granted being increased per summoned golem **PAST THE FIRST GOLEM** as well. In the PoB that will be linked below you can go into the "GOLEM VERSION" tree and click on and off the golems (mainly the stone, chaos, and carrion since their buff is not necessarily a damage increase) to (hopefully) see what I mean for the Hydrosphere and Storm Burst.
POB pastebin: https://pastebin.com/qL8F4HqN

**Comment by looqpool** [comment]
This is on version 1.4.170.25

**Comment by Wires77** [comment]
Liege of the Primordial doesn't care how many different types of golems you have, just the number of summoned golems.  PoB assumes you're at the maximum number of golems at all times, so you're always getting the 25% increased damage per summoned golem, even if you only have one golem selected in PoB (because then you'll have 9 of that golem).  The same thing is true for the increased effect of buffs per summoned golem.  Please check the Calcs tab to find a breakdown that shows the relevant stats:

![image](https://user-images.githubusercontent.com/1209372/105193942-b3d1db80-5afe-11eb-92ec-5ac3e73083ac.png)
