### ISSUE TITLE
Damage Conversion calculation issue (I think)

### ISSUE THREAD

**Issue by shrewdlogarithm** [PathOfBuildingCommunity/PathOfBuilding#2024]
I'm trying to understand damage calculations where conversion comes into play and I noticed something 

![convweird](https://user-images.githubusercontent.com/40507378/105596153-86e62880-5d8b-11eb-9989-4727e97d7e8e.jpg)

My inc/rec and more multipliers for the lightning calculation are higher-or-the-same than Fire when Fire has higher multipliers!?

Inc/red
Fire 1+1.37+.52+1.94 = 4.83
Lightning 1+1.37+.52+1.73 = 4.63 and not 4.9??

More
Fire 1.85 * 1.11 * 2.24 = 4.6
Lightning 1.85 * 1.11 * 2.02 = 4,15 and not 4.6??

Note: this build cannot do any damage other than Fire so the Lightning calculation is moot but still appears wrong?

Sorry if I'm missing something obvious but staring at the screen isn't helping and staring at the code is - erm - well...

BuildCode: https://pastebin.com/Hev8epRV

Note I've been messing about with this build in PoB - it's not an exact reflection of a real character at this point

**Comment by PJacek** [comment]
You can read about the conversion mechanics [here](https://pathofexile.gamepedia.com/Damage_conversion#Mechanics). Any modifier can only affect the final damage type once.
When you deal Physical to Lightning to Fire converted damage, the following modifiers apply:

1 + 1.37(global) + 0.52(physical) + 1.66(elemental) + 0.07(lightning) + 0.28(fire) = 4.9 increased
1.85(global) * 1.11(physical) * 2.02(elemental) * 1(lightning) * 1.11(fire) = 4.6 more

You made the mistake of counting elemental damage modifiers twice.

**Comment by shrewdlogarithm** [comment]
and I thought it was complicated before!!
The figures you're labelling 'elemental' are actually 'cold' are they not?  What has that got to do with a Phys as Extra Lighting calculation?
I also have zero idea where you're getting Inc/Dec 0.07 Lighting and 0.28 Fire/More 1 Lightning and 1.1 Fire from but at this point I think I've stopped caring ;)


    On Saturday, 23 January 2021, 17:00:40 GMT, PJacek <notifications@github.com> wrote:  
 
 


You can read about the conversion mechanics here. Any modifier can only affect the final damage type once.
When you deal Physical to Lightning to Fire converted damage, the following modifiers apply:

1 + 1.37(global) + 0.52(physical) + 1.66(elemental) + 0.07(lightning) + 0.28(fire) = 4.9 increased
1.85(global) * 1.11(physical) * 2.02(elemental) * 1(lightning) * 1.11(fire) = 4.6 more

You made the mistake of counting elemental damage modifiers twice.

**Comment by PJacek** [comment]
You have 166 increased elemental + 7 increased lightning applied to lightning
![lightning](https://user-images.githubusercontent.com/18018499/105609731-852c5d00-5dab-11eb-9e02-5b083511d7e6.png)
and 166 increased elemental + 28 increased fire applied to fire
![fire](https://user-images.githubusercontent.com/18018499/105609810-084db300-5dac-11eb-881f-d5a4e98945d7.png)
When converting from physical to lightning to fire all increases and reductions to both lightning and fire apply but _only once_. You can think about it as if the damage was physical, lightning and fire at the same time.
In the lightning damage column you see the sum for lightning and elemental because lightning is elemental, same for fire. Those values apply when you deal that type of damage but not necessarily when you convert though it.

> The figures you're labelling 'elemental' are actually 'cold' are they not?

You don't have any cold modifiers so only the generic elemental ones are displayed
![cold](https://user-images.githubusercontent.com/18018499/105610149-7c895600-5dae-11eb-9695-3ce32a9cca6a.png)

**Comment by shrewdlogarithm** [comment]
Thanks for the explains - I'm in WAY over my head at this point, I will study that and - erm - get back to killing things perhaps ;0
Thanks!
    On Saturday, 23 January 2021, 18:38:13 GMT, PJacek <notifications@github.com> wrote:  
 
 


You have 166 increased elemental + 7 increased lightning applied to lightning

and 166 increased elemental + 28 increased fire applied to fire

When converting from physical to lightning to fire all increases and reductions to both lightning and fire apply but only once. You can think about it as if the damage was physical, lightning and fire at the same time.
In the lightning damage column you see the sum for lightning and elemental because lightning is elemental, same for fire. Those values apply when you deal that type of damage but not necessarily when you convert though it.


The figures you're labelling 'elemental' are actually 'cold' are they not?


You don't have any cold modifiers so only the generic elemental ones are displayed
