### ISSUE TITLE
Abyss Jewel in shield is not taken into account.

### ISSUE THREAD

**Issue by Mijati** [PathOfBuildingCommunity/PathOfBuilding#2049]
It appears that Abyssal Jewels socketed in Shields (I've not tried other items) don't have an impact.

https://pastebin.com/XPu8dAeY - Example pastebin with a shield and jewel.

When the shield is set to equipped it correctly displays an Abyssal socket for it. However, inserting a jewel with various physical damage to attacks in it does not impact the DPS calculations. I've confirmed via in-game tool-tips that the jewel will increase my DPS (in case if for whatever reason abyssal jewels in shields were weird in game).

I've tried even adding life to the jewel and that is not taken into account either, so it's not just an issue with DPS calculations it appears.

**Comment by zao** [comment]
There's a check to ensure that only jewels in slots that are below the abyssal socket count are considered:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/46175fc3e24c26f81757b5f70630494b79c7a817/Modules/CalcSetup.lua#L422-L430

This `slotNum` is however incorrectly assigned for any `slotName` that contains a number like `"Weapon 2 Abyssal Socket 1"` due to finding the wrong set of digits in the name:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/46175fc3e24c26f81757b5f70630494b79c7a817/Classes/ItemSlotControl.lua#L30

Changing the code to anchor the match to the end of the `slotName` with `"%d+$"` seems to produce the correct `slotNum`.

**Comment by Wires77** [comment]
Fixed in v1.4.170.26
