### ISSUE TITLE
Trinity Support Damage Calculation wrong

### ISSUE THREAD

**Issue by wunschzettel** [PathOfBuildingCommunity/PathOfBuilding#2052]
Dear dev Team, 

It seems like the Damage calculation of Trinity is too high.
When I set 50 resonance Charges as Default I should be getting aroung 50-60% more Damage (5%more dmg per 5 resonance charges and the ele penetration)
related Pob can be found here: https://pastebin.com/jmGHFPPi

Moreover Melee Physical damage support dps increase is  not calculated Correctly. As seen in the PoB above and here: https://pastebin.com/pcfrJZJ4.
It should give at least 49% more damage.(+ the increased attack damage for Quality). Both PoBs give me less than 49% more damage, which I can't explain myself.

Thanks for this wonderful Tool and keep up the good work!

**Comment by Regisle** [comment]
The extra damage is almost entirely from the penetration, as you have no other sources of pen, if I disable the resistance/pen it gives the correct 50% more damage, as for melee physical damage support, this is due to having sources of flat elemental damage, and thus it does give the correct amount of more damage for the physical portion
