### ISSUE TITLE
Martial artistry bug.

### ISSUE THREAD

**Issue by wolfwing1** [PathOfBuildingCommunity/PathOfBuilding#2118]
Maybe this is like last time and missing something, but while the item mentions giving 1% attack speed per passive, when slotted doesn't actually seem to increase it and when it's a item you can slot doesn't mention it eitehr.

**Comment by Wires77** [comment]
This may be related to #2096, due to the colon in the name.  There is a fix for that going into the next release.

@ALT-F-X It seems like the jewel is still working in old builds, but may not be getting parsed in new builds/imports.

**Comment by ALT-F-X** [comment]
Hmm, I mean the build was old but I didn't have the jewel in it and had to add it for the example. I'm unsure about the difference between adding the jewel in the items tab and importing a build with this jewel already equipped.

Either way if you're confident this issue will be fixed in the next release then this is a non-issue.

**Comment by wolfwing1** [comment]
Thanks, it's a bit of a experimental build for me so curious about stuff :>

**Comment by Wires77** [comment]
@wolfwing1 I'm going assume this is fixed in v1.4.170.26, but feel free to re-open this issue if you're still seeing it
