### ISSUE TITLE
Ancestral cry grants incorrect melee strike range

### ISSUE THREAD

**Issue by Aggnog** [PathOfBuildingCommunity/PathOfBuilding#2136]
Hello,

Ancestral cry grants +1 strike range per 5power instead of +2 strike range per 5 power. Meaning you need 30 power in the options to get the maximum of +6 instead of 15. 

Best regards

**Comment by randomflyingtaco** [comment]
Ancestral Cry shows less strike range than the listed amount because it is applying the uptime calculation to strike range.  So with a 4.9 second duration and an 8 second cooldown you have 61% uptime on the extra strike range and 61% of +6 range is 3.7 which gets rounded down to +3 range.
If you want to see your peak stats instead of average stats, use the "Warcry calculation mode: Max Hit" on the Configuration tab.

**Comment by Aggnog** [comment]
Makes sense, closing in that case.
