### ISSUE TITLE
Still issues with Skeleton Archers with Phantasmal Summon Skeletons

### ISSUE THREAD

**Issue by MrHeartless246** [PathOfBuildingCommunity/PathOfBuilding#2239]
**What happened?** - Phantasmal Summon Skeletons which summons archers which use projectiles show no bonuses from proj skills like Awakened Chain, Awakened GMP or Vicious Projectiles etc.

**What were you trying to do?** - Accurately calculate the damage with various skills using different gem setups with Phantasmal Skeleton Archers.

**What steps will reproduce the bug?** - Use the Phantasmal Version of Summon Skeletons, set it up in a 6 link chain and see that adding any of the above mentioned skills does nothing. When I unchecked them in my POB upon installing the update it actually RAISED my damage. 

**Does it reproduce every time?** - Yes it does, I also think Phantasmal Skeles should only have a drop down for Skele Archers rather than all 3 as they all give very wildly different numbers. For example you literally cannot summon standard warriors with the skill so there should be no standard Summon Skele drop down.

**Provide a build code**: https://pastebin.com/rqFaJEB3

Hope this helps. 

Kind Regards,

**Comment by Wires77** [comment]
Awakened Chain and Awakened GMP both say "Supported skills deal x% less damage", so unchecking them will in fact make your damage go up.  This is accurate, and seems to be working fine:
![image](https://user-images.githubusercontent.com/1209372/108762118-4fe36e00-7515-11eb-8200-6d255b7b4baa.png)

Vicious Projectiles Support should probably work, so that will have to be looked into.

Summon Skeletons has always shown skeleton casters and skeleton archers as well, even though you literally can't summon them without Dead Reckoning or phantasmal summon skeletons, so I doubt this piece will be fixed, as it's a pretty minor bug.

**Comment by Wires77** [comment]
Upon further investigation, Summon Skeletons actually is not supported by Vicious Projectiles in-game.  If you find proof to the contrary, feel free to show it and re-open this issue.

![image](https://user-images.githubusercontent.com/1209372/108766159-693ae900-751a-11eb-9253-e00c21da56d2.png)

**Comment by MrHeartless246** [comment]
Thank you
