### ISSUE TITLE
Top Node wrong nodes

### ISSUE THREAD

**Issue by EdwoG** [PathOfBuildingCommunity/PathOfBuilding#2258]
I have this bug on every build.

Not 100% sure for other node power options, but

Total DPS +Top node + power per point 
=doesnt show the notable with highest total DPS per point

https://pastebin.com/Pe44bnXf
![image](https://user-images.githubusercontent.com/56611968/108955510-9698ab80-766e-11eb-9206-2da6739f0a3d.png)

(also on the side, its really hard to tell apart wich notables have more power. maybe making them orange additionally to making them brighter can help)

**Comment by Wires77** [comment]
Power per point is a simple calculation of the node's power divided by the points it takes to get there.  So the notable here is 3583.5 / 2 = 1791.75, while the small node is higher at 2508.4, so it gets highlighted.

Admittedly, this is less useful than the total including both nodes, but was done initially because of performance issues.  #2250 will make this more clear in the future.
