### ISSUE TITLE
Effective "Health" Pool Calcs

### ISSUE THREAD

**Issue by turokix** [PathOfBuildingCommunity/PathOfBuilding#2264]
* **What happened?** Various fields under the 'Effective "Health" Pool' section of the Calcs tab have semantic errors in their calculations
* **What were you trying to do?** Determine EHP values against various forms of damage
* **What steps will reproduce the bug?** Use one of various skills/keystones/enchants that affect potential "Health" pool
* **Does it reproduce every time?** Yes
* **Provide a build code:** https://pastebin.com/8UaQ51sA

For the build in the pastebin, multiple things effect EHP: Molten Shell, Molten Shell Buff Effect (from enchant), Divine Flesh, Mind Over Matter, various forms of damage taken conversions, and reduced/less damage taken.

Regarding Molten Shell and its effect on **Guard**/**Total Pool**:

Molten Shell's Buff Effect enchant bug is covered in #2245.

Molten Shell's text specifies "Damage from Hits" as being taken from the buff before life, but the guard value is added directly to the "Total Pool" which is also used by "Effective DoT Pool."

**ES Bypass**
Appears to be working correctly with Divine Flesh.
![ESBypass](https://user-images.githubusercontent.com/4359484/109067076-0c773400-76bc-11eb-8907-4bb59039351c.png)
![TotalPool](https://user-images.githubusercontent.com/4359484/109067081-0e40f780-76bc-11eb-92cf-55df06d3612f.png)

**Mind Over Matter**
Calculates your combined Life/Mana pool as MaxMana / HitToMana * HitToLife, rather than MaxLife + Min(MaxLife / HitToLife * HitToMana, MaxMana). For the build in the pastebin, this calculates to 5292 + Min(5292 / 0.7 * 0.3, 3115) = 5292 + 2268 = 7560.
![MindOverMatter](https://user-images.githubusercontent.com/4359484/109067216-316ba700-76bc-11eb-947e-8cbd130a2628.png)

**Total Pool**
"Mana through MoM" uses MaxMana rather than Min(MaxLife / HitToLife * HitToMana, MaxMana).
Guard is added directly to Total Pool despite only applying to damage from hits - there probably needs to be a separate Total Pool field for DoTs or for Hits.
![TotalPool](https://user-images.githubusercontent.com/4359484/109067081-0e40f780-76bc-11eb-92cf-55df06d3612f.png)

**Maximum Hit Taken**
Appears to have issues when dealing with converted damage types - it uses the minimum of the MaxHit for each element (ignoring conversions) multiplied by the ratio of damage taken as that element. This leads to converted elements having higher max hits compared to the more resisted element that the damage is being converted to. The correct formula should be MaxHit = TotalPool / Sum(RatioToElement * ElementTaken)) - as an example, for a 50/50 conversion of cold to chaos, with 85% cold mitigation and 92% chaos mitigation, it should be 31689 / (.5 * .15 + .5 * .08) = 275,556.
![MaximumHitTaken](https://user-images.githubusercontent.com/4359484/109067610-bce53800-76bc-11eb-85da-a2e60b799165.png)

**Effective DoT Pool**
Calculations use Total Pool, which includes Guard (which does not affect DoTs).
![EffectiveDoTPool](https://user-images.githubusercontent.com/4359484/109067862-15b4d080-76bd-11eb-9491-ca6b3fac7950.png)

**Effective Hit Pool**
I'm not exactly sure how 'Average Number of hits you can take' is calculated. I would imagine this to take into account flat damage reduction, armor, and dodge/block chances, but it is unclear if this is the case.
These calculations presumably use the same formula as Maximum Hit Taken, as chaos damage is the least effective pool despite being the type with the greatest mitigation.
![PoBCalcs](https://user-images.githubusercontent.com/4359484/109067737-eb631300-76bc-11eb-9cee-956945448cae.png)

**Comment by Regisle** [comment]
Molten shell buff effect breaking it has been known since we added it, its pretty hard to fix without handling guardskills specially (which we will likely do in the future so that we have the possibility of scaling them by uptime)

ES bypass is correct

MoM is actually correct, the number above effective life is the amount of life you can have given that amount of mana you have and your MoM value, its not calculating your total pool, in this case if you had 7268 life it would leave you with 7268 + Min(7268 / 0.7 * 0.3, 3115) = 7268 + 3115 (rounded) = 10383

Total pool, again MoM calcs is correct afaik and yes guardskills (and also aegis for that matter) should likely not be applying directly to the total pool, likely need to have a separate pool for dot setups as these do not apply to dots

Both max hit taken and EHP have the issue with conversion, this was known when I implemented it and although I have a few fixes none of them are viable (mostly via stuff approaching too close to simulation territory), this was done as a compromise to fix issues where the "total pool" value was different between damage types being converted from/to, this happens with different values of MoM/ES bypass/aegis that only apply to some damage types, this although fixing that issue does cause this new issue, which overvalues takenas slightly
its not summing the values in the final box, its taking the minimum, it arrives on that number by taking the calculated number and dividing by the conversion value (in the case its 31689 /0.1 (actually smaller than that, this is a rounded value) /0.5 (the amount going to that pool), again known to be incorrect have a fix planned, not sure when itll happen (theres multiple people looking at it atm and this isnt the only issue it has, eg armour mitigation is also wrong for max hit)

Effective dot pool, yeah should probs have its own total pool, as stated above, this is an easy fix Ill try to get around to

effective hit pool, theres actually a whole row missing which shows how 'Average Number of hits you can take' is calculated, but yes it uses a similar formula as max hit to calculate the number of damaging hits it would take to kill you (based on enemy hit damage, via config or value based on enemy life if config is empty), ceil that (as you need to take the full hit to die, you wont die before the hit is finished) and then factor in chance not to be hit, chance not to take damage when hit etc

**Comment by TheArisen** [comment]
Same issue here. Divine Flesh just doubles the dmg  you can take which is not right. Build that showcases that https://pastebin.com/vraCJnRX

**Comment by Helyos96** [comment]
@TheArisen Please see my PR at https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2276. It fixes some issues with max hit taken calculations, mainly when it comes to conversion and/or armour. Your PoB is correctly handled with it for instance.

It's unlikely to be merged for other reasons, but you can always check it out locally if you wish.

**Comment by Regisle** [comment]
The only remaining issue here is the max hit taken when the build has damage taken as, that should be somewhat fixed by #4120 and theres also already an issue for that #1930

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5196
