### ISSUE TITLE
Add warning when exceeding Jewel limit

### ISSUE THREAD

**Issue by ppoelzl** [PathOfBuildingCommunity/PathOfBuilding#227]
Timeless jewels have their own limit "1 Historic".

**Comment by TheAtomicOption** [comment]
I'd argue this is in some ways a feature since it makes comparing the jewel in two different locations easier by entering all the small passive info, then slotting the jewel in both spots and toggling allocation of the jewel nodes.

Should probably have a warning of some kind instead of forcibly preventing players from putting the jewel in and seeing its effects.

**Comment by LocalIdentity** [comment]
Limiting jewel makes comparing them difficult, so adding a warning to the warning list when you exceed the jewel limit is a better solution
