### ISSUE TITLE
Chance to poison on bows does incorrectly not affect spells in PoB

### ISSUE THREAD

**Issue by giniyo** [PathOfBuildingCommunity/PathOfBuilding#2301]
How to reproduce:

1 Pick chaos/phys spell in pob
2 Use bow with chance to poison/poison damage suffix
3 Damage will change, chance will not, while both will work ingame

SS 1: no poison chance [bow](https://prnt.sc/10ca6mm)

SS 2: poison chance [bow](https://prnt.sc/10ca7ny)

**Comment by ALT-F-X** [comment]
Thanks for the pictures but fill out the bug report form correctly and we'll be able to help you.

Specifically:
`* **Provide a build code:**
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.`

**Comment by giniyo** [comment]
> 
> 
> Thanks for the pictures but fill out the bug report form correctly and we'll be able to help you.
> 
> Specifically:
> `* **Provide a build code:** Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.`

Build code: https://pastebin.com/DYmNXPR9
PoB version: 1.4.170.27

**Comment by ALT-F-X** [comment]
Well thanks for the report, unfortunately this is cause by a limitation in how PoB works regarding GGG's language.

In more specific terms, how we implement mods in PoB is by reading or "parsing" the text and doing what it says. GGG is normally very consistent in their terms, but this a problem that comes up time to time. "What if they're not consistent?" well... PoB is screwed. 

So simply put almost every time GGG uses the words "x% chance to Poison on Hit" on a weapon it's a local mod to attacks with that weapon, examples I would point to are "Morteme Morsu" or "Taproot". Now the exception to that is the mod you have. It, for whatever reason, is a global mod but is using the same wording as other local mods.

One thing you could do is add the words "with spells" on the end of the modifier line to make it work with your build but unfortunately there's nothing we can do because GGG is using the same string of words to mean two different things.

**Comment by giniyo** [comment]
> 
> 
> Well thanks for the report, unfortunately this is caused by a limitation in how PoB works regarding GGG's language.
> 
> In more specific terms, how we implement mods in PoB is by reading or "parsing" the text and doing what it says. GGG is normally very consistent in their terms, but this a problem that comes up time to time. "What if they're not consistent?" well... PoB is screwed.
> 
> So simply put almost every time GGG uses the words "x% chance to Poison on Hit" on a weapon it's a local mod to attacks with that weapon, examples I would point to are "Morteme Morsu" or "Taproot". Now the exception to that is the mod you have. It, for whatever reason, is a global mod but is using the same wording as other local mods.
> 
> One thing you could do is add the words "with spells" on the end of the modifier line to make it work with your build but unfortunately there's nothing we can do because GGG is using the same string of words to mean two different things.

Ahhh.. i see, i thought maybe this was undiscovered since spell-poison-bows aren't used that much. Thanks for the lengthy explanation! I'm fine with it working ingame, not usually sharing my builds publicly.

**Comment by dskinner** [comment]
> how we implement mods in PoB is by reading or "parsing" the text and doing what it says

Is this the case in the strictest sense? Or is there not a context the parsing works within that could account for such?

**Comment by ALT-F-X** [comment]
I don't believe PoB receives mod tags from character imports or in-game pastes.

**Comment by dskinner** [comment]
Right. I mean given the qualifiers of non-unique, elder influenced, chance to poison (and any other qualifiers I may be over looking to ask this question), is it reasonable to know this line of text functions on spells if the line is evaluated within the context of these stated qualifiers? All of which are part of the pasted text

**Comment by ALT-F-X** [comment]
I don't think so no. We had a small discussion in the developer discord when this issue was first posted and we didn't have a solution to the presented problem. We don't have anything in place that contextualizes item mods to other mods.

**Comment by melink14** [comment]
With respect to:

> One thing you could do is add the words "with spells" on the end of the modifier line to make it work with your build but unfortunately there's nothing we can do because GGG is using the same string of words to mean two different things.

I tried to add "with spells" as mentioned here and it didn't appear to change the chance to poison in the calcs tab.
https://pastebin.com/412CTEmr

**Comment by QuickStick123** [comment]
Fixed a bug where Suffix modifiers on Weapons that grant increased Damage with Poison and chance to Poison on Hit were granting a global version of the chance to Poison on Hit stat, rather than a local version. Existing items have been updated to the local version.

**Comment by melink14** [comment]
> Fixed a bug where Suffix modifiers on Weapons that grant increased Damage with Poison and chance to Poison on Hit were granting a global version of the chance to Poison on Hit stat, rather than a local version. Existing items have been updated to the local version.

For future reference, this is a quote from the [3.19 patchnotes](https://www.pathofexile.com/forum/view-thread/3293287) meaning that the behavior in game mentioned in this thread was a bug and now PoB and the in-game implementation will match once the new league launches.
