### ISSUE TITLE
Latest build alters a build's damage drastically - 1.4.170.28 (2021/03/04)

### ISSUE THREAD

**Issue by pHiney** [PathOfBuildingCommunity/PathOfBuilding#2311]
RE: https://pastebin.com/WZEfDnm5 (from https://www.pathofexile.com/forum/view-thread/3024717)

I had just opened PoB and had imported the build. It reported approx 7.5 million dps.

Then the update appeared, so i accepted that. Now DPS is 2.9 Million.

Now i don't mind. Just wanted to alert you in case all those fixes were not intended to change damage like this.

thanks
X

**Comment by Wires77** [comment]
The DPS didn't change, but the numbers are in the same location, so it would appear that they did.  This release we added support for cooldowns on various skills factoring into a skill's cast rate and DPS.  Previously, some skills would assume average damage and not have a DPS because of the cooldown.

Old version:
7M total damage per Ignite - Assumes you hit once and let them burn, so you want to know the total damage per skill use

New version:
2.9M DPS inc. ignite - Assumes you're using the skill constantly, so letting the burn go for the full duration doesn't matter.

**Comment by pHiney** [comment]
OK, thanks
