### ISSUE TITLE
The old "power report" was way better. Please give us an option to stick to the old feature.

### ISSUE THREAD

**Issue by hellzer** [PathOfBuildingCommunity/PathOfBuilding#2423]
Previously you could just tick show best node box - fast and simple. Now you have to open an extra window and wait for everything to load up. While it does provide more information, I personally find it not as convenient as it used to be.
Now you can't see percentage increases and stats while hovering your mouse onto nodes without entering a power report menu.

:(

**Comment by coldino** [comment]
New functionality is basically the same as old functionality - except instead of ticking a box you click a button. The delay you're seeing now was also present before but not as obvious as it just appeared as subtle changes in the node colours. (unless you have Full DPS mode selected - that's slower because it simply has more work to do)

The big visual change is that it takes up a chunk of screen space. Maybe this can be improved so there's no space taken when all you want to do it hover over nodes on the tree.
