### ISSUE TITLE
crashing after couple of minute after launching

### ISSUE THREAD

**Issue by ZoneAssaulter** [PathOfBuildingCommunity/PathOfBuilding#2502]
* **What happened?**
* I launched the app and it crashed after a couple of minutes. the problem repeats it self everytime for the last month and a half
* **What were you trying to do?**
* make several builds and import some others
* **What steps will reproduce the bug?**
* just about anything even idling in the app
* **Does it reproduce every time?**
* yep
* **Provide a build code:**
* even with an empty pob the bug happens... but for an example: https://pastebin.com/Er2ra2CV
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
* dont think there are any helpful screenshots that i can take since theres no error message

**Comment by Wires77** [comment]
What Windows version and graphics card are you running on?  Try updating your graphics driver if you haven't recently.

**Comment by ZoneAssaulter** [comment]
Im using windows 10 pro and i have an rtx 3070 with updated drivers

**Comment by renews** [comment]
+1

**Comment by Lothrik** [comment]
I experienced the same thing yesterday while working on a new build, PoB just crashed silently. I just decided to save my builds much more frequently to avoid losing changes. Windows 10, RTX 2070, 465.89 drivers from Mar 31, 2021.

**Comment by ZoneAssaulter** [comment]
the issue still persists even after a few patches now...

**Comment by ImVexed** [comment]
Also experiencing this, it's incredibly frustrating to lose an entire build because it randomly crashes before you've saved....

Is there anything that can be done around at least not losing a build to a random crash? Maybe do it like VSCode or other editors that save a working copy until you hard save it to your desired location?

I usually have multiple instances of PoB open for days at a time with no issues, but I'll open a new instance, import a build, play around with a few things, and then it will instantly close it's window, and I'll get the startup dialog (with all the fast moving text of things loading..) for a second or two before that instance of PoB vanishes without a trace. 

None of the other instances will be effected but this has been a constant for months now across multiple re-installs and updates.

Not sure if there's logs anywhere that could provide insight but this is an incredibly frustrating issue to have.
