### ISSUE TITLE
Ignite Damage Calculation Bug

### ISSUE THREAD

**Issue by Ragestyles** [PathOfBuildingCommunity/PathOfBuilding#2601]
Fireball Ignite Damage does not get increased by Cruelty-Support's Buff that grants more damage over time multiplier, but instead increases the multiplier with the "more damage with hits" portion of the gem, which is false.

https://pastebin.com/TSWB9VL2 my current PoB to reproduce the bugs

**Comment by Boregore** [comment]
I think it's a bug in Cruelty Support and not Ignite (I think title should be renamed to help the devs). For Exsanguinate PoB is only showing increased Hit Damage and no increase in DoT damage.

Since the "x% more DoT" part of Cruelty is based off of hit damage % of monster life, it would be nice to add a field to "Configuration" where one could enter the monster life to base the effect of cruelty on.

**Comment by foxi** [comment]
For reference, the official calculation ist:

> At gem level 20, The Cruelty buff provides 15.85% more damage over time to skills supported by Cruelty when the hit does 0.01% of the monster's maximum life and 50% more damage over time to skills supported by Cruelty when the hit does 3.2% of the monster's maximum life.

Source: https://www.reddit.com/r/pathofexile/comments/mr1ijx/ggg_please_explain_cruelty/gujknss/

**Comment by QuickStick123** [comment]
Fixed by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3207.
![image](https://user-images.githubusercontent.com/31533893/178727598-2e65adee-d765-4132-8487-7a4a560d2d3b.png)
