### ISSUE TITLE
Temporal Chains + Blight interaction

### ISSUE THREAD

**Issue by StillProphet** [PathOfBuildingCommunity/PathOfBuilding#2689]
Using Temporal Chains linked to Blasphemy Support increases the "Skill duration" of Blight in the "Calcs" section (as it should).
However, this increase in duration is not factored into the DoT DPS of the Blight skill when selecting the "Maximum stacks" option for calculation purposes.

Skill Duration without Temporal Chains:
![image](https://user-images.githubusercontent.com/83215925/116067429-6cbd2e80-a689-11eb-9c3c-a1dcdba4d151.png)

DoT DPS at maximum achievable stacks (in this case 15/20) without Temporal Chains:
![image](https://user-images.githubusercontent.com/83215925/116067658-a5f59e80-a689-11eb-94f1-d7a27cc8448b.png)

Skill Duration with Temporal Chains:
![image](https://user-images.githubusercontent.com/83215925/116067528-7fcffe80-a689-11eb-8305-2a216c6c9da5.png)

DoT DPS at maximum achievable stacks (now theoretically 19/20) with Temporal Chains:
![image](https://user-images.githubusercontent.com/83215925/116067735-bd348c00-a689-11eb-963d-69c2f4121482.png)

**Comment by ALT-F-X** [comment]
I was able to reproduce this with an old build of mine that wasn't using temporal chains: https://pastebin.com/XadQt3Xd

Seems like anything under the "debuff expires slower/faster" modifier doesn't affect calculations on max stacks.
![image](https://user-images.githubusercontent.com/5727264/116090798-dc232600-a669-11eb-8097-ea1e19288485.png)

**Comment by ALT-F-X** [comment]
The code making the duration calculations looks good, I don't know where the bug is.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/77ae3a8563c4bbdefe022cf20cbea06499d1bf0e/src/Data/Skills/act_dex.lua#L7763

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/77ae3a8563c4bbdefe022cf20cbea06499d1bf0e/src/Modules/CalcPerform.lua#L1913

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/77ae3a8563c4bbdefe022cf20cbea06499d1bf0e/src/Modules/CalcOffence.lua#L188
