### ISSUE TITLE
Path of building isn't starting

### ISSUE THREAD

**Issue by delyan-georgiev** [PathOfBuildingCommunity/PathOfBuilding#2711]
When I try to run the Path of building I got this error

![image](https://user-images.githubusercontent.com/6060805/116779636-306e4180-aa80-11eb-960a-651fb5d2286d.png)

**Comment by zao** [comment]
Could you please post what Windows version (can be seen in `winver.exe` or "About your PC"), GPU model and GPU driver version?

Is this a new problem on this particular computer or has it worked before, and have there been any major changes done?

**Comment by delyan-georgiev** [comment]
Windows 10 Pro version 20H2, GPU NVIDIA GeForce GTX 960M, GPU driver version 466.27, it is a new problem on this pc, the 1.4 version was working. This issue appeared after installing v2.1.0

**Comment by myzperfect** [comment]
i got it problem too windown 10 pro version 1511 amd ryzen 5 3600

**Comment by ppoelzl** [comment]
@myzperfect Windows 10 version 1511 is EOL for more than three years by now: https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1511-end-of-servicing. Please understand that we cannot offer any support for outdated operating systems. I recommend updating your installation. If not for PoB, then due to security concerns.

**Comment by myzperfect** [comment]
@ppoelzl  wow update already i can use pob thank you very much
