### ISSUE TITLE
Power report crash

### ISSUE THREAD

**Issue by woke-kromcrush-horde** [PathOfBuildingCommunity/PathOfBuilding#2720]
latest build: 2.3.0
crash when trying to mak a power report for dps (all types)

hangs usually but sometimes crashes with error box
![POB ERROR](https://user-images.githubusercontent.com/77876578/116841777-3101f780-aba8-11eb-9700-92a3b22b68b1.JPG)

**Comment by ppoelzl** [comment]
What's up with the capitalisation? Please fill out the issue template you've deleted, and maybe we'll be able to help you.

**Comment by AlphaJuliettOmega** [comment]
@woke-kromcrush-horde  @ppoelzl this is a **duplicate** of: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2492

I haven't been able to use Power Report / any passive tree reporting to plan a build at all this league except for hovering my mouse over each specific Passive Tree node and taking a guess for the power per point / min max strategy.

I do hope the original issue isn't too difficult to solve, because it's making me not able to plan my passive tree like I'm used to.

**Comment by Wires77** [comment]
Closing as a duplicate, then.
