### ISSUE TITLE
Catalysts are not able to be added to belt/ring/amulets unless they are corrupted

### ISSUE THREAD

**Issue by Ataraxey2** [PathOfBuildingCommunity/PathOfBuilding#2727]
Using POB community fork 2.3.0

When looking to add Catalysts to any ring/belt/neck both rare and unique, the Catalyst option does not show up unless you do the following:
- add corrupted modifier
- select a corruption implicit

If you corrupt with no implicit, Catalysts still do not show up. 

Some corruption implicits, like "added item quantity" or "added item rarity" also do not let Catalysts show up

Example screenshots:
No corruption: https://gyazo.com/ec5593341bfd088c6c20a20a9494ca88
Corruption no implicit added: https://gyazo.com/dde5a324d8b609701c4f43573f92c133
Corruption with added implicit: https://gyazo.com/0bdbba5e8e5b81f70eaf8174b59cbe58

**Comment by Wires77** [comment]
When you import an item from in-game, PoB doesn't have a way of knowing what mods have what catalyst tags.  When you build an item from within PoB (this includes adding corrupted implicits) we know the catalyst tags that can apply to those mods.

> Some corruption implicits, like "added item quantity" or "added item rarity" also do not let Catalysts show up

This is because those mods aren't affected by catalysts at all.
