### ISSUE TITLE
Explosion Trap DPS includes Lightning damage to attacks.

### ISSUE THREAD

**Issue by Davst** [PathOfBuildingCommunity/PathOfBuilding#2739]
Thank you for reporting an issue.

* **What happened?**
Looking at rings, noticed that removing this ring meant losing damage, checked ingame and this is incorrect.

![image](https://user-images.githubusercontent.com/3330933/117148487-8ad80c80-adb6-11eb-87e6-e17c100771c6.png)

* **What steps will reproduce the bug?**
Equipping or unequipping a ring that has Lightning damage to attacks using Explosive trap as dmg. Might also count for other dmg to attacks, not sure.

* **Does it reproduce every time?**
Yes
* **Provide a build code:**
https://pastebin.com/stFHjWYA

**Comment by ALT-F-X** [comment]
It's not because of the Lightning Damage to Attacks, it's because removing the ring changes the Wise Oak elemental penetration to cold to lightning because of your resists changing which is a DPS loss. 

Toggling Wise Oak off and then removing/equipping the ring does not change DPS.

Working as intended.

**Comment by Davst** [comment]
Ah. Sorry. Mistake on my side
