### ISSUE TITLE
Item editing not available when importing from poe account

### ISSUE THREAD

**Issue by Dreathorian** [PathOfBuildingCommunity/PathOfBuilding#2814]
Adding catalyst quality is not possible when importing from a poe account.
item editing when creating a new empty build or importing one from pastebin is alright.

here the differences:

PoE import
![mine](https://user-images.githubusercontent.com/74142437/119062896-19b07000-b9d8-11eb-9cac-3f760102c90d.png)

pastebin/empty
![other](https://user-images.githubusercontent.com/74142437/119062899-1a490680-b9d8-11eb-98b3-99cde2ef682f.png)

**Comment by Wires77** [comment]
This is a limitation because of the information GGG gives us on character import.  We don't know the exact mods that the item uses, as one phys damage mod line can actually be two hybrid mods that combine together, instead.  Now that there is support for advanced item copying from the game, which does tell us the exact mods, perhaps this can be improved, but for now it's not something we can fix.
