### ISSUE TITLE
Support Gems and tree nodes don't show change to DPS when main skill is a minion

### ISSUE THREAD

**Issue by Groar90** [PathOfBuildingCommunity/PathOfBuilding#2891]
As in topic, when trying to make a minion build I noticed support gems and tree nodes don't show how much dps would I get when allocating them. Also tried getting someone elses pob to check if I maybe didn't check some box to enable that but it's still the same.

POBs: https://pastebin.com/hac7Lg1e
          https://pastebin.com/EwwtgmxM

![obraz](https://user-images.githubusercontent.com/53011792/124788226-74326b00-df49-11eb-8bac-b560b612a554.png)

![obraz](https://user-images.githubusercontent.com/53011792/124789029-34b84e80-df4a-11eb-8129-695bf32a4b56.png)

**Comment by benjaminysmall** [comment]
Hi @Groar90, can you confirm that I'm interpreting the issue correctly?

When selecting/deselecting nodes on the tree and selecting/deselecting support gems, the Minion statistics (Attack/Cast Rate, Total DPS, etc) in the left-hand panel *are* correctly getting recalculated, but the tooltip when you hover over those nodes and gems only shows effects on *you*, not any effects on your *minions*.

So a solution to this would be to extend the tooltips to have two sections:

- Allocating this node [Enabling this gem] will give you:
- Allocating this node [Enabling this gem] will give your minion:

Is that correct?

**Comment by Groar90** [comment]
That's correct.

Previously it just showed as your damage since it's selected as your main skill anyway and the tooltip when you hover should interact with your selected main skill. Not sure when this was changed since I didn't play minion skills for a while.

**Comment by philipdickinson** [comment]
I raised this change on Discord, and figured I should transcribe my messages here too. TLDR is that "stat differences" labels on nodes do not correctly display changes to minions in 2.3.0. The colouration of nodes for node power does still work exactly like it did before though, and allocating the nodes does correctly change the values displayed in the main skill pane and the calcs screen.

repro steps are easy: (v 2.3.0)
* create a new character (witch or templar show it most easily since they have minion damage nodes near start)
* add skill (e.g. unlinked level 1 Raise Zombie)
* set as Main Skill in left panel
* mouseover any minion damage/minion life nodes and you'll see no changes in the label
* allocate any minion damage/minion life nodes and you will see changes in the left panel (and in calcs etc)

Like the reporter of this issue, I am not totally sure when this changed because the last time I interacted with a minion build in PoB it still worked correctly.

**Comment by philipdickinson** [comment]
This also affects skill selection too, it turns out. Turning auras on and off _does_ still correctly affect calcs (including left panel) for minions, but the mouseover information doesn't show anything related to the minions. This worked not too long ago.
![pob1](https://user-images.githubusercontent.com/970955/126428340-a5d8613f-a86c-44b2-817b-9f1745f91926.png)
![pob2](https://user-images.githubusercontent.com/970955/126428341-c9c5b4e0-a5a5-4f0b-a6a5-4c5f03161c6e.png)

**Comment by Wires77** [comment]
This is fixed in the dev branch when we release 2.4.0
