### ISSUE TITLE
Incorrect mana regen from arcane surge (50 flat mana regen from level 1 gem)

### ISSUE THREAD

**Issue by OrcFace** [PathOfBuildingCommunity/PathOfBuilding#2937]
refer to above

**Comment by Lothrik** [comment]
This is caused by:
`mod("ManaRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "Arcane Surge" }),`
in sup_int.lua
It should be:
`mod("ManaRegen", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "Arcane Surge" }),`

This should be resolved once we have the 3.15 patch data, along with most everything else broken with gems right now.

**Comment by PJacek** [comment]
Fixed in v2.5.0
