### ISSUE TITLE
High GPU Usage on Builds screen

### ISSUE THREAD

**Issue by thattopnote** [PathOfBuildingCommunity/PathOfBuilding#3195]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When Path of Building is open and in focus on the Builds screen, it should not consume many resources as it is a static 2d page.

### What is the actual behaviour/value?

When Path of Building is open and in focus on the Builds screen, GPU usage climbs significantly. This may be caused by uncapped FPS on this screen.

### How to reproduce the issue

Open Path of Building. If a build is open, click the Back button to return to the Builds screen. Observe high GPU usage on this screen, which decreases when opening a build or when the program loses focus in Windows.

### Build code

```shell
N/A
```

### Screenshots

![image](https://user-images.githubusercontent.com/89938903/131727444-9afcb7d6-1077-405d-94e0-9339295679e2.png)

**Comment by zao** [comment]
Path of Building attempts to use swap control extensions to do Vertical Sync but this can be overridden by choices in your GPU control panel or with software like RTSS.

It should tell you in the console (Ctrl-`) if it has found the extension with `using WGL_EXT_swap_control`, this should always be in use as there's no setting to control it.

**Comment by thattopnote** [comment]
I see, I had changed my global settings in my GPU software while troubleshooting FPS issues in other programs. I was able to fix it by enabling VSync for this program.

**Comment by knasen88** [comment]
could this not be patched by hardlimiting the amount of frames rendered globally or something? I was at 99% cpu in build screen and 50ish on the passive tree, limiting through nvidia specifically for pob.exe to 20fps made it into a 1-10% drain when focused.

**Comment by zao** [comment]
There's two primary drawbacks to limiting framerate:
- interactive performance feels bad with less than the refresh rate;
- sub-scripts in PoB have callbacks dispatched in the render loop, limiting the framerate affects their speed.

If a user has configured their system in a way that VSync doesn't take, that's kind off out of our hands. Manual timing loops for such short refresh intervals are quite hard to get right due to scheduler granularity and I really don't want to bump the system into a more granular timer just to unscrew what someone might've done when there's perfectly fine VSync in place.
We do have artificial limiting when defocused as computation performance isn't as important then.

Some of the pending improvements to our renderer should lessen the need for capping below refresh rate as well, as it's way more effective in the future.
