### ISSUE TITLE
Bleed DPS with Crimson Dance isn't being shown correctly on the sidebar

### ISSUE THREAD

**Issue by rxh4133** [PathOfBuildingCommunity/PathOfBuilding#330]
Bleed DPS on the sidebar is shown with one stack of bleeding instead of the number defined in the configuration tab. It calculates and shows Bleed DPS correctly under the Calcs tab.
![image](https://user-images.githubusercontent.com/21953468/76143674-657f2f80-6047-11ea-8dbc-da52b26062e4.png)
I imported this from my current character, made some changes in game, and then imported again. Not sure if that's related.
Running version 1.4.157.7 of the LocalIdentity fork.
https://pastebin.com/MKnCukdU

**Comment by mithlug** [comment]
It also doesn't calculate Bleed DPS correctly, hovering over shows a 0.7 modifier. With Crimson Dance that one becomes 0.35

**Comment by Nostrademous** [comment]
@mithlug the `50% less Damage with Bleeding` is applied in the `Total More:` section. And multiplier like that are associative. Applying it to the base bleed percentage would double dip and make the calculation in correct. Since `Less` is the inverse of `More` we are leaving it it in `Total More`. 

The original issue has been resolved a long time ago for this issue.
