### ISSUE TITLE
Essence worm makes auras with % reservation to not reservate mana at all no matter where they are socketed

### ISSUE THREAD

**Issue by Arkegon** [PathOfBuildingCommunity/PathOfBuilding#3493]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Socketed aura gems that reserve percentage mana should only reserve no mana when socketed on the Essence Worm Ring.

### What is the actual behaviour/value?

If Essence Worm Ring is being used, any aura gem with percentage mana reservation reserves no mana even if it is not socketed on the ring.

### How to reproduce the issue

Use a Essence Worm Ring and a aura gem that reserves percentage mana anywhere but the ring.

### Build code

```shell
https://pastebin.com/1c5gqtEV
```

**Comment by SaloEater** [comment]
There is a problem with too low reservation efficiency value )

**Comment by eakaye** [comment]
There's some ambiguity over how less than base reservation efficiency will be handled. The devs indicated that they're designing existing items and passives so that they'll have roughly the same effects on reservation in isolation; only when you start stacking them do diminishing returns kick in. If net reduced efficiency is calculated as though it were increased, but then the resulting modifier is added to your reservation multiplier instead of subtracted, then one Essence Worm would make your reservation become 2 - (1/1.8) = 1.44 times base, which is close to the original value. On the other hand, if reduced reservation uses the same formula as increased, then your reservation becomes 1/(1-0.8) =5 times base. With 100% reduced efficiency from two Worms, non-zero reservation becomes infinite and thus impossible. PoB currently doesn't prevent you from over-reserving, it just shows a negative amount of unreserved life or mana. Presumably this behavior is just its way of avoiding a divide by zero.

**Comment by Wires77** [comment]
Fixed in 2.14.0, to my memory
