### ISSUE TITLE
Incorrect body armour base stat values

### ISSUE THREAD

**Issue by etojuice** [PathOfBuildingCommunity/PathOfBuilding#3703]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Evasion rating from body armour should display a value of 898

### What is the actual behaviour/value?

Evasion rating from body armour shows an incorrect value of 899

### How to reproduce the issue

1. Evasion breakdown in Calcs tab, hover over value next to "Base from Armours"
2. Items tab, hover over body armour

### Build code

```shell
https://pastebin.com/M5SkTwNb
```

### Screenshots

In PoB:

![изображение](https://user-images.githubusercontent.com/5415811/139847856-f1e828d1-c403-4edb-af8f-5d0af86a6e5d.png)
![изображение](https://user-images.githubusercontent.com/5415811/139847985-6ddd08cb-1874-4e64-8c8d-877f0229e27e.png)

In Game:
![изображение](https://user-images.githubusercontent.com/5415811/139848669-742f9dee-22ec-4359-a758-2d180d36683d.png)

**Comment by Wires77** [comment]
Interesting edge case.  The base armour value in-game would be 879.  This would make the percentile value 19.53%.  Since I coded this to round to 2 digits, it becomes 20%, pushing the base value calculation to 879.6, which gets rounded up, giving you the extra evasion rating.  I should be rounding to 4 digits, I suppose, to have more accuracy without introducing floating point errors
