### ISSUE TITLE
Ignite DPS calculations are not correct or not explained enough

### ISSUE THREAD

**Issue by 8Times** [PathOfBuildingCommunity/PathOfBuilding#3717]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

So a friend of mine fell into the trap of trusting POB and thought that he needs to avoid any "#% chance to ignite" because it would reduce his Ignite DPS instead of increasing it.

Naturally you would expect more damage when you increase the chance to ignite and not less damage.

Something like this is what I expect the Ignite DPS to be:

(Hit Damage * crit chance * 1,5 + Hit Damage * ignite chance * (1 - crit chance)) / 2

### What is the actual behaviour/value?

It took my some time and help but I think I understand what the problem is:

The Ignite DPS doesn't calculate the average Ignite DPS but some really weird and confusing total which I have no utter understanding as the Calcs details don't explain the "portion of instances creaty by x" part in the slightest.

### How to reproduce the issue

1. new pob
2. add weapon with added fire damage
3. make copy of item and add "5% Chance To Ignite"
4. equip sword without ignite chance
5. see less Ignite DPS when comparing both swords

### Build code

```shell
https://pastebin.com/QFzUk5tg
```

### Screenshots

Without Chance to Ignite:
![image](https://user-images.githubusercontent.com/13020561/140238688-15c89386-2e3b-47fd-9156-4958b707cfdb.png)

With Chance to Ignite:
![image](https://user-images.githubusercontent.com/13020561/140238709-8a342e08-a3a9-4685-81d0-b376c24b421d.png)

**Comment by Wires77** [comment]
There's nothing really wrong math-wise, here.  PoB assumes you will crit or ignite at some point when calculating ignite DPS if you can crit or ignite at all, based on the Ailment setting in Configuration.  When you add ignite chance, suddenly some of your ignites are no longer coming from crits, so the average DPS goes down.

Portions of instances created by crits would be 100% if you didn't have any ignite chance, but since you do have 5%, 5% of those 95% of hits where you don't crit are going to be ignites.  i.e. `.05 * .95 = 4.75%`.  Then you have to calculate the proportion relative to the total: `4.75% / (4.75% + 5%) = .487`

Everything in PoB is done by averages, so really this number is an average ignite DPS.  That's really the only way to do it without simulation, unfortunately, and PoB is not a simulator, just a calculator.
