### ISSUE TITLE
Poison Mastery and "Low Tolerance" Notable Passive Skill

### ISSUE THREAD

**Issue by LukasOfLockless** [PathOfBuildingCommunity/PathOfBuilding#3750]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

If enemy is set to 0 stacks of poison in configuration, then "Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage" is supposed to appear in poison damage calculations total increased.
this descriptor can be in poison mastery or as a notable in chaos damage over time medium cluster jewels

### What is the actual behaviour/value?

"Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage" only appears as text and doesn't change any values in calcs

### How to reproduce the issue

any arrow skill,
link to poison cluster notable
pick  "Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage"
link to jewel socket
add medium cluster chaos damage over time with "Low tolerance" for the  "Poisons you inflict on non-Poisoned Enemies deal 300% increased Damage"
set poison stacks to 0 in configuration
check poison calculations. there's no 300% increase for any of the things.

### Build code

```shell
https://pastebin.com/YhXDdjHd
```

**Comment by deathbeam** [comment]
But this is not how it works at all. Even if you have poisons on enemy set to 0 in config, this config value applies only to stuff like vile toxins. If you set it to 0 and that would activate the 300% inc damage mod then you would be inflating your damage because the damage increase would still count for all your poisons. The damage increase should apply only to first poison (the simple solution would be to divide the damage increase by max poison stacks on enemy i think).
