### ISSUE TITLE
Is Charged Dash Hit Rate Being Correctly Calculated?

### ISSUE THREAD

**Issue by Cabledragon** [PathOfBuildingCommunity/PathOfBuilding#4083]
Most Recent Update (v2.14.0) [2022/02/05] stated added support for proper Charged Dash calculations but I'm not sure they're implemented correctly. (I didn't want to submit this as a bug until I know I'm not off my rocker.)

The expected behavior: Changing Movement Speed should have SOME impact on your hit rate.
The current behavior: Changing Movement Speed has NO impact on your hit rate.

In the current version Charged Dash appears to have a Hit Rate nearly half of your Attack Speed which is unaffected by your movement speed.

Charged dash should have a hit rate based off of your Movement Speed AND your Attack Speed.<sup>1</sup>

I believe the hit rate should be: T*(S/2)
Where T = the time it takes you to reach maximum stages
And S = the maximum stages reached in that time

The amount of maximum stages is calculated by (A*T)
Where A = Attack Speed
and T = the time it takes you to reach maximum distance 

And T is calculated using movement speed and the maximum distance of the illusion can travel.
(There's a funky calc for this on the wiki)

<sup>1</sup>Note: This is all according to my limited knowledge of Charged Dash's Calculations and this assumes 100% accuracy.

<sub>P.S. - This should probably be a feature request, but I feel like Hit Rate should have its own breakdown on the stats page. Sometimes it's different than Attack Rate for reasons that aren't always obvious.</sub>

**Comment by Wires77** [comment]
There was some discussion around using movement speed in the PR here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3125
@VaticViolet had some ideas for more improvements around this skill, and I believe that was one of them, but didn't get added in time for the release.

**Comment by Cabledragon** [comment]
This is fine, I just wasn't sure what exactly was going on but that PR helped fill me in. I doubt I'll be using charged dash anytime soon again as main skill anyway since they gutted channeling skill support with the skill tree rework. I blame it all on cyclone.

**Comment by VaticViolet** [comment]
Oooh! I can chime in here!

Just to fully clarify, the movement speed DOES need to be looked at, but _only_ for the final wave damage, in so far as finding out your max stages. It's important for something like overkill damage, stun chance, non-damaging ailments, etc. The hit rate itself won't be affected, as the hit rate for CD is exactly half your attack speed. The wiki (both wikis, actually), while rife with misinfo on this skill, is right in this case:

https://pathofexile.fandom.com/wiki/Charged_Dash
> While channeling you will release a pulse for half of your stages

and then goes further to contradict itself, weirdly.

There's so much wrong with the documentation of this skill, which is sorta why I worked on it. even GGG's wording implies the final wave should get bonus ignite damage, which it doesn't. It's just such a confusing skill with confusing math. Not just the stage calculation, but even this part is wrong:

>  The damage per second is only slightly lower over all while channeling

because the effective dps of the charge/release "phase" and the max charges "phase" are equal:

While charging: 

> Channeling damage = 121% * 1.6 / 2
> Release damage = 121% * 1.6 * 0.75
> Together: 121% * 1.6 * 0.5  +  121% * 1.6 * 0.75 === 121% * 1.6 * (0.5 + 0.75) === 121 * 1.6 * (1.25) === 242% Effective DPS

While at max charges:

> 121% * 1.6 * 2.5 / 2 === 121* 1.6 * 1.25 === 242% Effective DPS

(Technically higher than cyclone!)

Exactly equal, but virtually noone knows that, since its so confusing, bleh. That's not even touching how it interacts with dual wielding. Weird skill, but I'm confident the hit rate is correct, at least. 

>I doubt I'll be using charged dash anytime soon again as main skill anyway since they gutted channeling skill support with the skill tree rework. I blame it all on cyclone.

Agreed! Extremely annoying, I'll probably keep playing CD tho lol. Really fun skill, even if it _is_ the anti-meta cyclone.
