### ISSUE TITLE
Attack rate stuck at "1"

### ISSUE THREAD

**Issue by Anvoc** [PathOfBuildingCommunity/PathOfBuilding#4092]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I am increasing attack speed on my build I expec tthat Attack rate increases.

### What is the actual behaviour/value?

When I add attack speed, Attack rate stays at 1

### How to reproduce the issue

1. Select Main skill Blade Flurry
2. Check attack rate

### Build code

```shell
https://pastebin.com/0b9W1PZR
```

### Screenshots

![image](https://user-images.githubusercontent.com/99149220/152705110-1868a1e0-72c4-4a90-a64c-c13cfa828019.png)

**Comment by AlphaJuliettOmega** [comment]
Misstyped my password, locked myself out so you beat me to issue creation.

This bug is related to the fix for non-channeling GC builds, their calculation was overcomplicated and showed more dps than they really had.

I don't know how to check Blade flurry attack rate with it stuck on 1, it makes getting to the 10aps / full release under 0.6 seconds impossible.

I think the PR on this issue broke it for Blade Flurry:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3190
References this PR:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3220
It's probably this that breaks Blade Flurry calcs:
```
skillData.timeOverride = 1
```
Channeling skills should show attack rate like before because it's useful.


Overwhelm physical damage vs overwhelm damage with hits vs you impale with hits vs impale on hits etc all still seem to be an issue with General's Cry. (some nodes show damage increase but supposedly don't do anything)
Might be related so mentioning it in case.
Related threads:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4050
