### ISSUE TITLE
Wrong aura name at Lightning Golem configuration

### ISSUE THREAD

**Issue by extinn** [PathOfBuildingCommunity/PathOfBuilding#4125]
With Summon Lightning Golem enabled in the character's skills, it will show "Enable Wrath Aura" in the skill options in the Configuration.
The Lightning Golem does not in fact give you the Wrath aura, but rather "Storm Nimbus". This was confusing to me, until I checked the official wiki. 

Edit:
Highlighted ability:
https://pathofexile.fandom.com/wiki/Summon_Lightning_Golem#:~:text=Storm%20Nimbus%3A%20Temporary%20aura%20that%20adds%20lightning%20damage%20to%20attacks%20and%20spells%2C%20lasts%204%20seconds%2C%20uses%20default%20aura%20radius.

**Comment by jurgyy** [comment]
It's called "Lightning Golem Wrath" ingame so I don't know where the Wiki got that from.

![image](https://user-images.githubusercontent.com/22032197/154362919-27a64543-76b4-46c4-b6ff-f3844007215e.png)

**Comment by Lothrik** [comment]
"Storm Nimbus" was added by a user named Raicss on the old Fandom wiki back in 2016. They haven't been active since early 2017, and I can't find any reliable way to contact them. Their source at the time was "personal testing" which doesn't exactly tell us much.

As it currently stands the buff is explicitly named "Lightning Golem Wrath" in-game (and this matches the datamined name ``LightningGolemWrath``) so that's the only thing that makes sense to display in PoB.

If this changes in the future we'll probably rename it, but for now.. the wiki is wrong and needs updating, not PoB.
