### ISSUE TITLE
Error in Combat Focus calculations

### ISSUE THREAD

**Issue by Ghaduo** [PathOfBuildingCommunity/PathOfBuilding#4150]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Unless I'm misunderstanding something, entirely possible, I should be getting more DPS with Elemental Hit when I add combat focus jewels while I have Avatar of the fire. Right now it is showing more DPS in both the Full DPS and the Fire damage MH hit damage with them unequipped.

In game, my tooltip DPS goes down by a significant amount when I remove either or both jewels.

As you should be able to see in my attached picture, the "Prismatic skills deal 50% less" is being calculated before the conversion - It is my understanding that the reduction happens when the skill deals damage and therefore after the conversion takes place.

### What is the actual behaviour/value?

Right now it is showing less DPS in both the Full DPS and the Fire damage MH hit damage with them equipped.

As you should be able to see in my attached picture, the "Prismatic skills deal 50% less" is being calculated before the conversion.

### How to reproduce the issue

1. Select Elemental Hit, Fire attack as the main skill.
2. Toggle Equipped/Unequipped Combat Focus Jewels from socket 1 and/or socket 2 in the items page.
3. View differences in Full DPS and Calculations/MH Hit Damage(Fire).

### Build code

```shell
https://pastebin.com/4jXpwJZ5
```

### Screenshots

![POB Combat Focus errors](https://user-images.githubusercontent.com/91360647/153762691-c6f30da6-f2c7-4239-ae37-a6a83f924f33.png)

**Comment by Lilylicious** [comment]
You are incorrect in your assumption and this behaviour is expected.

When you convert something to another element, it is affected by the modifiers to any previous element it was. 100 lightning that is converted 100% to fire is affected by both increases/reductions to fire damage and lightning damage.

As a result, equipping combat focus jewels reduces the damage that you get from conversions by 50%. This was an intended nerf to the build a long time ago by GGG.

In PoB, we don't simulate multiple hit types. The benefit of combat focus is that you can focus on just modifiers to fire damage, rather than have those modifiers be 1/3rd as effective. That effectively means that in PoB, equipping combat focus has no benefit because it doesn't simulate what happens when your percentage of fire damage hits goes from 33% to 100%.

**Comment by Ghaduo** [comment]
> In PoB, we don't simulate multiple hit types. The benefit of combat focus is that you can focus on just modifiers to fire damage, rather than have those modifiers be 1/3rd as effective. That effectively means that in PoB, equipping combat focus has no benefit because it doesn't simulate what happens when your percentage of fire damage hits goes from 33% to 100%.

Ok, I see. I was incorrect in my understanding about the conversion, but there is no modifier for the chance to choose making the jewel calculation unhelpful. Thanks for your response!
