### ISSUE TITLE
[3.17] passive skill points wrong

### ISSUE THREAD

**Issue by jojo5528** [PathOfBuildingCommunity/PathOfBuilding#4157]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

passives skill tree is still the old same.
the new 3.17 passives skill points is 24 from quests

### What is the actual behaviour/value?

i just see for now, trying to import my character to passives tree and it said that my tree require more level

### How to reproduce the issue

1.just import some of your skill tree from character
2.in the game, your character level is lower than POB
3.check in game /passives and its said 24 points from quests
4.POB give only 19 points from quests

### Build code

```shell
https://pastebin.com/hM455i5M
```

### Screenshots

![image](https://user-images.githubusercontent.com/49547185/153989013-d91419e8-c161-40aa-b9a8-78e9b715dd6e.png)
![image](https://user-images.githubusercontent.com/49547185/153989066-894a1c1f-3720-4a21-9532-1ca1728fd370.png)
![image](https://user-images.githubusercontent.com/49547185/153989086-badaa707-b8c1-4f6b-aa49-0082d14e7bc3.png)

**Comment by Wires77** [comment]
What is happening here is that PoB assumes certain skillpoints at certain levels, since that's what level you end each act at.  You're right on the cusp of getting to level 68, at which point PoB would give you 3 more quest skill points for beating act 10, bringing the total to 24 points (including the bandit quest).  When importing a character, we have no knowledge of the quests you've completed, so if you complete some earlier than their level, PoB won't know and will assume you're a higher level.
