### ISSUE TITLE
physical reduction

### ISSUE THREAD

**Issue by Leiyer** [PathOfBuildingCommunity/PathOfBuilding#4204]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

hi good mornig, I am doing the build for my scion but the physical reduction is wrong, when I use the farrul fur. according to the game it gives me 41% but in pob it only gives me 8%

### What is the actual behaviour/value?

different physical reduction.

### How to reproduce the issue

only i put my farrul fur

### Build code

```shell
code?
```

### Screenshots

![image](https://user-images.githubusercontent.com/100086289/154853607-061d1d2b-5332-4d66-aa69-16ef25ca8ada.png)
![image](https://user-images.githubusercontent.com/100086289/154853729-a2580ec7-24d3-42a2-b9f7-30b974d95aeb.png)

**Comment by PJacek** [comment]
Armour effectiveness depends on the amount of damage received.
I'm not sure where did you get the 41% and 8% from but your in-game screenshot shows 48%. PoB will show you that if you set the enemy to normal monster and default damage (normal monster damage times 1.5)
![image](https://user-images.githubusercontent.com/18018499/154856941-e69a090d-37cb-4a75-a646-d32e2057fb65.png)
You see 28% probably because you set the enemy to Sirus 
![image](https://user-images.githubusercontent.com/18018499/154856998-0df0b1e2-e368-43b5-a89e-fddf07f55268.png)
You can see the damage currently used for calculations in the Calcs tab 
![image](https://user-images.githubusercontent.com/18018499/154857069-cf942765-ced5-4bdb-8045-b1c009106704.png)

**Comment by Leiyer** [comment]
i see, i have sirus activated, jajaja sorry
