### ISSUE TITLE
Checking 1 aura effectives node make me go from effetive life 159k to 12 million and is capped. [Doryani's prototype]

### ISSUE THREAD

**Issue by Nivius** [PathOfBuildingCommunity/PathOfBuilding#4208]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

not go into the millions? from one node, seems highly wrong. the pool is then "capped" apprently. and nothing more changes from more efficivness

Doryani's prototype is involved. as uneqiping it makes it "normal"

### What is the actual behaviour/value?

normal math of effectivness

Doryani's prototype is involved. as uneqiping it makes it "normal"

so, there is something wrong with the Doryani's prototype math.

### How to reproduce the issue

https://pobb.in/1UTsL33ztGDQ

Check and Uncheck "influence" the big aura node at CI.
can get a minor same issue from checking effectivness between shadow and sion. 

Doryani's prototype is involved. as uneqiping it makes it "normal" 

### Build code

```shell
https://pobb.in/1UTsL33ztGDQ
```

### Screenshots

https://i.imgur.com/ZuxjVyX.png
https://i.imgur.com/11jhCSA.png

https://imgur.com/a/rMyDKKc

**Comment by Regisle** [comment]
This is due to the gain on block affecting it, both doryani and aura effect increase es and armour, and your set vs normal mob, if you set vs boss it no longer does this (as you no longer gain more damage than you take)

We have discussed disabling gain on block from ehp calcs by default as no other recovery is currently included

**Comment by QuickStick123** [comment]
Closing as we have a config option disable eHP on block that will display reasonable values for no on block recovery. https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4227
![image](https://user-images.githubusercontent.com/31533893/178139685-684ecb2a-ffda-4fc4-942b-c498afed4028.png)
![image](https://user-images.githubusercontent.com/31533893/178139667-d930c862-6c22-4221-80af-0d9baba0477e.png)
The reason it goes from 150k to infinite is due to it reaching a critical threshold on low damage attacks to recover all of the energy shield back. Increasing the damage or setting to a boss also fixes this.
