### ISSUE TITLE
Lethal Pride and Brutal Restraint jewels dont save their mods on unallocated nodes.

### ISSUE THREAD

**Issue by OmikronGamma** [PathOfBuildingCommunity/PathOfBuilding#4250]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When editing Brutal Restrain or Lethal Pride timeless jewels (right clicking on the node and then selecting bonus) it should be saved, whether its been allocated or not.

### What is the actual behaviour/value?

As of right now, only bonuses for allocated nodes are being saved.
Moreover, unallocated nodes keep their mods for the current "session" of PoB, meaning if reload build by going to build selection menu, changes are there; but if close then reopen PoB, changes are gone.

### How to reproduce the issue

1.Add bonus from Lethal Pride or Brutal Restraint timeless jewel ti unallocated node.
2.Save build.
3.Close and open PoB.
4.No added bonus on the node.

### Build code

```shell
eNqtWm1zGjkS_mx-hYqqrbqri_G88OrCu4VtbHMHDsvYyd2nlDw0oLVmxM5ocNit_e_X0gww6xgjlMQVPCOeflHr6VZLSfeXrxEnK0hSJuKLqltzqgTiUExZPL-oPj7cnLarv_xc6Y6pXHycXWaMq29-rpx09TPhsAKOclUiaTIH-Wmjyf-CmpY0lgsQ8Yj-JpJbMb2o3osYquSJxlMmN28hp2l6TyO4qAYhClcJTUOIp1e78RwYURYHInwGeZuIbKnNrhi8jMQUMYPR-OPkoWSUxWWj6PNJd8zpGpJAUklS_Lio9nDqdA7XNMJP1EZ5hqq8mtdqeG2n3Wm3W8169ext4WAJMN0KuTVvH3CcQH82g1CyFVwlTF4taBzuzDn75I7FjjIu2ZIzSEpeNfZJ3H2j3HX2qn8QkvLrcVCKUct3fL_ltNrNhtt6X07IwxP4zOTikmNELawo2cE8ZhIshceCpSL-jvmVRfevUcY5po8ZVkRPLLaKxojG9EqkBjEfshmYIfuBGW6CeWSGVF6OIcFMl-bOHiVQWAggFFhNjrFxjEhpHnbGLCT7gY2AhaFA7kqJt7eSXMPXLcpv7kMN4p1Bz9mvayWk3gUO-aZTr3833iKbrZrfrHc6zQ4Wss5eP_L54_bAIspH9CuLsghr4QN9hp3VerOGejY_rfeWcGffe2enCM8VdhCHZrx4jBNIIVmVNpj96v8uUKy0SVVXghOYQ2zm1BAgXNziLjyhEswyY4tqOO8GR2GNgqOAbwSnYShwRHCU4Kvg1DrvgY8Mz2eaTA0yN4Zkvg4WDLgBWseyLGIU07KAIR3KIkfOu7-iaTnBvQOzyeHliXh7W7IRYAeBElMw7ZvGifhNdWb8OLFeEoksMVyQHGw2g_FinbIQewrdkk5gmoVm5XDbYY7ECiLkuG5PsTfecX2f6CXHrtp05qiW86MkelLS8PlaTOdwlJHjJYJsucRMV3wxlbthCUY5ZaXd8NT3DqM_4snhii5NGjmVVKYGdmhjA0M2X8gY-0pzK69EzOeyoCJ9baZpAjc2cYM9slGDPBYvqHKhjp3pcWjc83ftyl4_Eoj_WBvr_xvcyEA_nmaJ4qixjdcS35rpnuljuXoaREuRSD14RXmYapWDeJlJEuszdcTS8MtTNpup43MVTST6zN-_uelfPQw-9QsvyiLpM-P8S5xFT-qEmf_elZUAdKUioeCcLlPAk3fMeJUwfAiUZIDFOZQGaOzGihP5YSzuomHCMHyHoeoYauCqPtUfxqkDtwEM14FyMA3Rw3oJasVTsygVRe4wVh-sDXD5OdhkWvq0bRJ0COnaALdtIgywfQ49xtUeZxKnERI93xxN0LhZJewpk0aM0u2_gQeqETaYVrnVM2K-CazoVAzMF33ZYWSxA5jQDtsEwyW6hhkgmY0SWReH_MCWl71NievqLEpJirXvFqL0co17yY0K6KsblYhKpBtEQ3WB-SBURaWhhGSYX2jOKE9VUSyruajKJMPBKcxoxtX4rxnlTK5VyS6NFiq0t-lCvKimJNejsjvFFRkO8296XBYqlJGNVT2jhwSAUN3PqRZSVdk8LPhSvh8dTLX1iKbo_Lqg-UUVqzNWdXxotNu-_8FvttvuB99ttvG50XDw02847Q9ux63XP9Tbba9dJRJNlu5v3VZxNZubUNZPuv0pZv30XunWA-URAvgokgDUWtU9PJFpJ5S4tpOrODnx6j8RFocJUFxVUrCO4NkB9x9C4ynJGZuD_-U6PxEpCOWcYNqrnKec5ARUtS_NYST_1ShrvuXiCbG9MMRdM1wXFnKvz3Zu5xM7ez2z7uNkmDu8kHKZnp-dvby81JZULsQMvuJxoRaK6GyJ8cElOtU746mK4FkP_1zO8e-yN4H2x_8k9eFzkLLTFY7npjaau_ll9iaS-ds2Znq1kO8SIh3CPC9QvCSFL8gHnQGKMOrhXsh8Bmpw86Lp9InBC0kB98tFIBPFkT-EiP6HHZznNmp-23PaOS3vgMoRXRYUVqCC0p2C0LhBXTOkWqITdpMXCvhf1OZ6nZrX8txO3n52BziDtOCyeg5A6qv7LIX8KuYz0KWI9bCymLcdCMTeJmE0xuF6nvd5DpxMcFiuz8nj_eDXx37lMskKTsgE9w9ZeWARdhppSv4NL8ArQ6DzDM7JEOZItMqnXOk56aUQ43LuBq4hXSQgdwP3SM2I7t4vKUdG0UreyCDFtt_UvzWKEZvA7-fEcyoTOmVZih6otq0yZJGiGrL6nLgV7A84C5nEr53Kn8WMz92__sRObw7nTq3x1zXEQgmoGwwWAhEz8o-G45y2Hcf5JxaeZ1W8kPhELrBm5G-I2cxvq9T7AUo3Mdoq9X-A0iLOW531H6Bzs1bjPENThUj0OhCaALkS8e8ZEnhKntZacoRymFaLyh1WFpGwUCcb9sYT5QnR_qgboMaGikU67kV4BxH-QcTmluBMpcM2LzBT9iZPOU-6AReb1j2HETd4oUvSe1qnKaZMUXEauyrjbFx6Q_S1mGcm9j7qUgiZWjr01lwOOHUJXB4pcoN74DPxjVzy3nLJtwuvWRC8HyRWt3OyaWetaR9NGz4dWIE7wLOEPNbQG0xq2tg5QD_sYlbqcuB4xb59Frk29up2XHDtmFc_vDwmgT1W7Vv0spy4Ud1pWPhjUQP9Q2am66ItP3L53o6yFb8aNkJGKWmyEFbzbFiH1bNY96ZdJvl29PWPZ1ndvuxbcNq1Dr5vQoi6CcjC7e9ofgxX0n4VmhastF-G76CLaUlWsoZZYw61iNxE3X14NiXGsw6vZbkwX0-b6fgGcXLtl6FuHa2GzWxM8sWe5Adc6kUZf2Nvyw-TeGDU10b6ckb_I5GIZ2yOiO7Z6__s-X99Rxyp
```

**Comment by Lothrik** [comment]
This is intentional, not a bug. If you want the conquered nodes to be saved across sessions you'll need to actually allocate them somewhere in the build. In the past all conquered nodes were saved regardless of allocation, making build files gradually balloon in size to the point where builds that should have been under 50KB were exceeding 1MB (and continuing to grow, as the unallocated nodes were cross-polluting across builds).

**Comment by Lothrik** [comment]
For future reference, this is the block of code that handles that behavior:
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/fc0707cf60d51f617da383abd14c2399b3fee701/src/Classes/PassiveSpec.lua#L184

It checks to see if a given node in the editedNode data (such as Quick Recovery or the two minor nodes leading to it) is actually conquered by a Legion Jewel (meaning that editedNode data existing makes sense and isn't unused garbage from another build entirely), and then it checks if that node is also allocated anywhere in the build (across every passive skill tree, even if there isn't any Legion Jewel socketed in those alternate skill trees).

It currently doesn't check the type (or number) of the Legion Jewel at any point during this (despite both of those properties resulting in different editedNode data being saved) &mdash; mostly because adding that was overly nitpicky and the conquered/allocated checks were sufficient to solve the ballooning file size issue.

A configuration option to disable these sanity checks could probably be added, but we would need to add more aggressive garbage collection (that I'm not even sure would work..) to prevent the original problem from popping back up. Doing something like this is very low priority considering how simple it is to just.. allocate the nodes you actually want saved. It doesn't even need to be in the same passive tree as the legion jewel. :)
