### ISSUE TITLE
"Is the enemy Brittle" should be an always on option in configuration

### ISSUE THREAD

**Issue by shrewdlogarithm** [PathOfBuildingCommunity/PathOfBuilding#4301]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

With the existence of the 'Brittle Boots' (drop brittle ground when moving - popular on AGs in particular) it's possible for anyone to be hitting 'brittle' enemies even if they don't have something like a Galesight equipped.

Currently it seems 'Is the enemy Brittle' only appears when PoB detects a suitable item??

This means someone using an AG or an item which isn't supported (such as the boots) you cannot see the effect of the bonus?

### Describe the solution you'd like

I think "Is the enemy Brittle" should probably be always visible - there are a number of issues in the DB for items which trigger it not adding it into PoB (mostly fixed) it but the existence of 'Brittle Ground' probably means it should just be 'always on'??

### Describe alternatives you've considered

You can workaround this by equipping - say - a Galesight, assigning Brittle % and then removing the item but that's a bodge at best and may stop working inadvertantly

**Comment by dyfrgi** [comment]
I've found that even if I switch to Galesight it does not work. Repro is to load this build https://pastebin.com/FvNnmyjc (or https://poe.ninja/challenge/builds/char/MrsDeath_/SadPandaArchMage?i=4&search=class%3DNecromancer, it's just taken from there), add Galesight, switch to it. You should see Brittle, but instead you don't. I also tried adding a The Interrogation jewel to the build and it *still* doesn't show up, so clearly there's something very wrong with the detection of this ailment.

**Comment by shrewdlogarithm** [comment]
I struggled with that too - it seems to work if you load a build which contains a suitable item but it doesn't always notice if you add one to an existing build!?

**Comment by Wires77** [comment]
> I've found that even if I switch to Galesight it does not work. Repro is to load this build https://pastebin.com/FvNnmyjc (or https://poe.ninja/challenge/builds/char/MrsDeath_/SadPandaArchMage?i=4&search=class%3DNecromancer, it's just taken from there), add Galesight, switch to it. You should see Brittle, but instead you don't. I also tried adding a The Interrogation jewel to the build and it _still_ doesn't show up, so clearly there's something very wrong with the detection of this ailment.

You don't see Brittle on this build because there's nothing on the build that deals cold damage, doubly so because it's a skeleton build (i.e. the skeletons don't inflict brittle, _you_ do)

Most of the config options are hidden by default because of the sheer clutter they induce, so if there's an easy way to detect if a build can enable them, PoB checks that.  The real fix here would be to properly support brittle ground, though it may be a further problem because AG buffs are currently unsupported in general.

**Comment by dyfrgi** [comment]
Interestingly, if I add a Frostbolt skill to it, the Brittle checkbox still doesn't show up with Summon Skeletons selected, but it does with Frostbolt selected. Fortunately it looks like it is taken into account for the Summon Skeletons, even though it isn't available to check until you pick Frostbolt.

I had tried adding a cold skill before, but it didn't work because I didn't select the skill. So, there's a workaround, and one that uses the "brittle" calculations rather than e.g. adding "Socketed skills have +5% to critical strike chance" on the body armor. Should be the same result for numbers, I think.

**Comment by Barcellera** [comment]
To add Brittle on ''For effective DPS'' table, just put Secrets of Suffering on Custom Modifiers box.

**Comment by LocalIdentity** [comment]
The brittle ground mod is now suppoted, if you just want brittle to show up you can add `10% chance to inflict brittle` to the custom mods box

**Comment by deathbeam** [comment]
Well there is PR for brittle ground but its not supported yet right (also my bad for not referencing this issue from the PR i actually kinda forgot to search if there is any issue for it open :d). But for reference the PR is here https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4443
