### ISSUE TITLE
Ephemeral Edge does not increase damage for Blade Trap skill

### ISSUE THREAD

**Issue by igorcastroo** [PathOfBuildingCommunity/PathOfBuilding#5006]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I believe it shouldn't be counting the damage for any skill

### What is the actual behaviour/value?

low damage

### Character build code

```shell
https://pastebin.com/WWdU7Kx6
```

**Comment by igorcastroo** [comment]
Attacks with this Weapon have Added Maximum Lightning Damage equal to 20% of your Maximum Energy Shield

this line does not count towards any damage

**Comment by QuickStick123** [comment]
The issue here is the mod wording isnt getting passed correctly as from reading the pre release infomation it was worded without the maximum in the wording so we assumed it didn't have it so the current ingame wording doesn't work. Try adding the ephermral edges from pob unique list in the meantime but it will be fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4952 unless there is some other issue with the implementation.
