### ISSUE TITLE
Purity of ice max res scaling with aura effect not correct

### ISSUE THREAD

**Issue by DanielSzemik** [PathOfBuildingCommunity/PathOfBuilding#5143]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Based on the character sheet, I need 90% increased effect of auras in order for a level 23+ purity of ice to grant me +10% max res, with 89% increased effect it only gives me +9% (according to character sheet in game)

### What is the actual behaviour/value?

According to PoB I would only need 85% increased effect of auras to get +10% max res.

### How to reproduce the issue

This is my characters PoB:
https://pastebin.com/ewxM1r8q 

According to it I could lose 5% increased effect of auras and not lose max res, but in game losing 1% increased effect of auras causes me to lose max res.

### Character build code

```shell
https://pastebin.com/ewxM1r8q
```

**Comment by QuickStick123** [comment]
Can you provide the character name and profile?

**Comment by QuickStick123** [comment]
This 5% discrepency seems to be caused by your old tree version in PoB which has the pre nerfed 15% effect of aura on you. This is currently not counted in the aura effect breakdown but does apply correctly. This mean in PoB with that tree version you can only have 85% and still keep the breakpoint. Updating the tree version fixes this.

![image](https://user-images.githubusercontent.com/31533893/196559214-a5ae9174-17bd-4c3b-b1ea-51f974df2ff3.png)

Screenshots taken on DEV where the aura effect breakdown is fixed. This might be in beta branch not sure.

Before
![image](https://user-images.githubusercontent.com/31533893/196559238-9289acd4-ba45-4a00-81d1-7c8e88224b4c.png)
![image](https://user-images.githubusercontent.com/31533893/196559143-88abe898-1051-48db-a415-3a56d3610f24.png)
After
![image](https://user-images.githubusercontent.com/31533893/196559259-d2cfbb4a-0970-4bea-9bad-929ceb7cbb33.png)
![image](https://user-images.githubusercontent.com/31533893/196559308-9a9b261f-b79e-4bca-9611-fe5252dcff5a.png)

**Comment by DanielSzemik** [comment]
Yeah, really sorry - don't know how I missed that

Thanks for the good work
