### ISSUE TITLE
"Trade for items" feature (one handed weapon) doesn't take into account "1% increased damage per 15 strength" mod on amulet

### ISSUE THREAD

**Issue by melink14** [PathOfBuildingCommunity/PathOfBuilding#5438]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

In general, it seems that the generated mod weights take into account global state of my character so I would also expect it to know that strength gives me increased damage.

### How does Path of Building behave?

The list of generated weights is missing strength as a damage mod despite it being enough to change the order of the results when sorting by weighted sum.

### How to reproduce the issue

1. Import build
2. Trade for new sceptre.
3. Notice that weapons with strength are not sorted as highly as they should.

Results might not be the same but here's example showing no strength in search (https://www.pathofexile.com/trade/search/Sanctum/r7kMQjZiQ). See screenshot for example where order was wrong due to it not being taken into account.

### Character build code

```shell
https://pobb.in/p7LqLc8hGAo6
```

### Screenshots

![image](https://user-images.githubusercontent.com/1176550/209286048-6e053f62-169f-4fbb-bfdd-94fa20d53789.png)

**Comment by QuickStick123** [comment]
This is impossible to fix sorry we have run out of mods we can search for otherwise we hit search complexity limit. For example the int gem mod gives around 0.7% and 55 strength roll would be about 0.6%. Everything else would obviously give more.
![image](https://user-images.githubusercontent.com/31533893/209287305-2de0b10d-756b-4048-b229-3ae8c06846d1.png)
![image](https://user-images.githubusercontent.com/31533893/209288678-f4054c0d-ba11-4144-a670-f44edcf0c453.png)
Some synth mods seem to be leaking in even when it is turned off which should be fixed in an upcoming patch but there isn't really anything we can do here.

**Comment by melink14** [comment]
Seems fair. I was just surprised when the lower ranked item gave mroe damage in PoB.

To the complexity point, there are several higher weighted irrelevant mods which I have to manually remove now that could make room for a more complete list but priority shouldn't be high for such marginal gains.

**Comment by QuickStick123** [comment]
There is a sorting option here that should fix that. There is currently a bug with that search option not using full dps but it will be the default and be fixed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5375
![image](https://user-images.githubusercontent.com/31533893/209290444-edf2f17f-9e75-4d36-abc5-0410ea8094dc.png)
