### ISSUE TITLE
Unable to import my account

### ISSUE THREAD

**Issue by Hextech89** [PathOfBuildingCommunity/PathOfBuilding#5480]
I play on my Xbox. I have logged into the path of exile website and made sure my account is set to not hidden. I have also tried to enter a POESESSID and still get nothing. the only thing i can think of is that my account name on the path of exile website is not the same as my Xbox name because i played on pc before it released on Xbox. My Xbox Gamer tag is Hextech Hero. My Account name on path of exile website is Desired_Chaos. Im able to log into my old pc account but i don't play the pc version anymore. Hope you can help.

**Comment by QuickStick123** [comment]
Can you provide a link you your account? Also you privacy settings should look like.
![image](https://user-images.githubusercontent.com/31533893/209823934-3132c37b-949e-42e9-9785-4cf92f79fced.png)
The most likely issue is due to having a space it isn't encoded correctly. You need to encode it like browser urls do with so "Hextech%20Hero"

**Comment by QuickStick123** [comment]
Desired_Chaos seems to load for me. 
![image](https://user-images.githubusercontent.com/31533893/209824402-e664b277-f591-4e5d-b4b3-51efc9ee0f8d.png)
