### ISSUE TITLE
Allow reordering of gems

### ISSUE THREAD

**Issue by ZzZombo** [PathOfBuildingCommunity/PathOfBuilding#573]
Also, an option to autosort added gems would be appreciated.

**Comment by Nostrademous** [comment]
This is not something we plan on implementing anytime soon.

**Comment by ZzZombo** [comment]
Please stop closing issues you have no interest in. Is there some kind of a race to reduce the amount of opened issues for the sake of having a low issue count? I hope not. Doing so reduces the visibility of them, unfairly I might add, why not let them sit there, maybe somebody eventually will find interest in implementing the changes necessary, but that's a bleak prospect with issues being swept under the rug. And to be clear, it's not the first instance of this occurring, and I find it wrong practice.

**Comment by Nostrademous** [comment]
@ZzZombo it's a matter of cleanup and accessibility honestly. Your reported issue is a feature enhancement that's a Quality-of-Life request for a single person thus far. It's not a "race" to reduce the amount of opened issue but rather a de-cluttering of the issues. We currently have a 9 page backlog of issues. The reason I close issues is to reduce the amount of pages people have to scan through to see if an issue they have experienced and are about to report has already been reported or not and thus not created duplicates (some people won't do this regardless of 1 or 20 pages of issues in backlog, but a non-trivial amount will).

If you are really interested in having your issue implemented and because it's not a PoB breaking design issue or a highly-requested QoL feature I highly suggested you try and implement it yourself if you can. Otherwise, it just won't happen honestly. 

I apologize if this reasoning is unsatisfactory.
