### ISSUE TITLE
Documentation on how to use the HeadlessWrapper

### ISSUE THREAD

**Issue by yuuls** [PathOfBuildingCommunity/PathOfBuilding#5958]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I've been trying to get the HeadlessWrapper to work, installed LuaJIT but running the .lua doesn't really achieve anything.

As you get this error:

`lua: HeadlessWrapper.lua:163: module 'xml' not found`

Is the intention for the HeadlessWrapper to only work when you clone the repository? Or am I supposed to put it in the installed PoB folder? Some guidance as to what is the expected way to use HeadlessWrapper or some examples of how to use it would be great.

### Describe the solution you'd like

Personally I'd like to see some instruction on how to load an XML build and then calculate the DPS for this loaded build.

**Comment by Wires77** [comment]
You need to set your LUA_PATH to include the libraries included with PoB.  E.g. `$env:LUA_PATH='C:\Users\trevo\git\PathOfBuilding\runtime\lua\?.lua;C:\Users\trevo\git\PathOfBuilding\runtime\lua\?\init.lua'; luajit .\HeadlessWrapper.lua` in PowerShell.  You can also get some ideas for what HeadlessWrapper can do by looking at the tests in the `spec` folder.

There isn't documentation because HeadlessWrapper.lua is not the primary focus for our development and can change at any time.  We use it for unit testing, and others like poe.ninja use it for their own purposes, but we don't provide much support in terms of features other than letting them know if there definite plans to break it in some way.  Internal function names can always change, so documentation might quickly go out of date.

**Comment by message** [comment]
@Wires77 does POB require `LUA 5.1` or it will work with `5.2+`?
