### ISSUE TITLE
Passives allocated from Crucible passive skill tree skills not showing as allocated on Passive Tree

### ISSUE THREAD

**Issue by Azryyal** [PathOfBuildingCommunity/PathOfBuilding#5972]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

When equipping a weapon that has a "Allocates X" from a Crucible Passive Skill Tree skill, the (regular) Passive Skill Tree **should** show that skill as allocated, as well as taking that allocated skill into account for all relevant calculations.

### How does Path of Building behave?

When equipping a weapon that has a "Allocates X" from a Crucible Passive Skill Tree skill, the (regular) Passive Skill Tree **does not** show that skill as allocated. I think that the allocation is taken into account for all relevant calculations, though this should be checked.

I'm unsure if this is an error for all such allocations, or is only a bug for "Allocates Prism Weave", the allocation I'm seeing the issue on.

### Character build code

```shell
https://pobb.in/hCfQwwY9Msxx
```

**Comment by QuickStick123** [comment]
You will need to manually remove the ` (crucible)` part at the end of the mod lines. This will be handled correctly in the next release by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5823 
It will look like:
![image](https://user-images.githubusercontent.com/31533893/230723154-206962d3-b2d2-487e-a84a-3ba7d82ba037.png)
Instead of:
![image](https://user-images.githubusercontent.com/31533893/230723178-40355da3-49fc-44ec-a6a6-85df9efb6dc3.png)

I will close this issue as the above PR has already been merged into the dev branch.

**Comment by QuickStick123** [comment]
The reason the notable in particular isn't working is it trying to allocate `Prism Weave (crucible)` mod which doesn't exist but is parsed in the general form.
