### ISSUE TITLE
Gem "Shopping List" please

### ISSUE THREAD

**Issue by witcheslive** [PathOfBuildingCommunity/PathOfBuilding#5975]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I am trying to level off of a guide that is only a PoB and has no associated text guide, and it is causing massive usability issues

### Describe the solution you'd like

I would like a view on the Skills tab where you pick the set, and it just has a flat list of all the gems you need for that skill set, i.e. this guide I am using has "Level 1 - 12" and I can just keep the list open as reference as I turn in quests and not have to click each socket group to remind myself of everything on there. Even better, if it would list when the skill can be obtained.

### Describe alternatives you've considered

i don't know bashing my head into the wall repeatedly because this game makes me feel stupid even after ive been at it for years and kind of know how to do some things but don't have every goddamned aspect of it memorized like everyone else seems to assume i and everyone else does

### Additional context

I am using this guide in particular, it's really good and a well made PoB but there's no text guide so I feel a bit out of my element here https://pobb.in/X_f0Te-hYxtj

**Comment by Nightblade** [comment]
I too prefer a flat-text shopping list, however there doesn't seem to be much dev interest in this idea.  What I currently do for each slot:
* Click the slot, press <kbd>ctrl</kbd>+<kbd>c</kbd> to copy it
* Click a blank line in notepad++, press <kbd>ctrl</kbd>+<kbd>v</kbd> to paste the raw slot text

Sample output (in notepad++ with some "User Defined Language" magic for colourisation):

![image](https://user-images.githubusercontent.com/23911/230750231-15d9f9e6-cb76-49d1-bf56-abfd687e39a6.png)


(If I have a good day or two I plan to generalise the current copy-paste function so that you can paste in different markup formats with nice colours in the Notes tab or the forums.)

**Comment by Wires77** [comment]
Path of Building is primarily focused toward build planning and optimization, and as such there is limited design or UI space left for leveling guides.  There are other people who have made specialized websites for this that do a much better job than PoB could do: https://heartofphos.github.io/exile-leveling/#/ is a good example.

FYI if you didn't realize, there are some things in the Notes tab for that build, though it still lacks a full list of gems.

See related issues in this comment: https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4228#issuecomment-1050651358
