### ISSUE TITLE
Adj. Trigger Rate using the wrong cooldown variable

### ISSUE THREAD

**Issue by lilliedesu** [PathOfBuildingCommunity/PathOfBuilding#6260]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

cooldowns trigger based on server tick rate breakpoints

### What is the behaviour in Path of Building?

The Adj. Trigger Rate value in PoB is using the base trigger cooldown value instead of the server tick rate adjusted value, leading to a higher attack rate than expected for DPS calculations

### Character build code

```shell
https://pobb.in/yOrop0I3uQEr
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/59601160/15173ec1-3441-4d1c-871b-c2bf33febecd)

**Comment by Paliak** [comment]
This seems to be a flaw in the way current implementation of manaforged handles the case when mana cost (_mana_ cost specifically, other costs don't count for manaforged) of triggered skill is 0.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/19818870af754cc17b9fa8e16c026670f20932e6/src/Modules/CalcOffence.lua#L1523-L1528

Should be correctly handled on the beta branch since #4599 was merged but i don't think the maintainers have released a new version for download yet.

![obraz](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/91493239/e437a776-e284-4633-9c09-ea190f009efa)

**Comment by QuickStick123** [comment]
This was fixed afaik.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/31533893/0e54fce7-c6a7-4ae2-ae8a-2bf8d01511d8)
