### ISSUE TITLE
Unable to dl files from Fork

### ISSUE THREAD

**Issue by SaeRoYi** [PathOfBuildingCommunity/PathOfBuilding#637]
Hi, I just installed pob on my laptop and changed the manifest file according to the instructions. 
After opening pob, it shows dling 225 files. When it finishes, it gives me this error:

Update Check Failed!
One or more files couldn't be downloaded.
Check you internet connectivity,
or try again later.

can anyone help?

**Comment by Cameron9551** [comment]
I am also having this issue. Hopefully someone knows a fix

**Comment by d3xless** [comment]
Same issue

**Comment by hofawd** [comment]
Same issue here as well.
The Update goes through all 225 files, but then fails with the same message the OP has.
My version uses "Layout 2" from the install instructions...
`<Source url="https://raw.githubusercontent.com/PathOfBuildingCommunity/PathOfBuilding/{branch}/" part="program"/>`

**Comment by Nucleoprotein** [comment]
Same here.

**Comment by tvinki899** [comment]
same

**Comment by Spacedragoon** [comment]
same

**Comment by dodspunkare** [comment]
Bump.

**Comment by Tomhet** [comment]
Reinstalled the latest PoB version, modified the manifest file and it downloaded the update on startup, now it's working

**Comment by NotRyian** [comment]
Anybody figure this out? I tried reinstalling PoB and then modifying the manifest and it still didn't work.

**Comment by BSpawns** [comment]
Having the same issue... Is anyone working on this? Would be great to know i'm not going crazy because I obviously have internet and it's obviously trying to download 225 files...

**Comment by dodspunkare** [comment]
In my previous installation of PoB I had no 'Path of Building'-folder in the 'ProgramData'-directory. I ran PoB directly from a folder on my Desktop. So I had no choice than to edit the manifest-file in that folder. This is what gave me the error at the time of bumping this thread.

After reading the reply from @Tomhet I did what I should have tried right away, but didn't, because reasons*.
1. Removed the folder on my Desktop (but saved the Builds-folder).
2. Downloaded the .exe-installation file from Openarl's github page.
3. Installed it in the default path and did _not_ launch it after installation.
4. The installation created the 'Path of Building'-folder in ProgramData with the manifest-file according to 'Layout 1' in the installation guide for this community fork. I copy-pasted the correct line of code from the guide. Saved and launched PoB.
5. Success.


* I avoided it since I didn't want to lose builds and shared custom items,

**Comment by NotRyian** [comment]
> 
> 
> In my previous installation of PoB I had no 'Path of Building'-folder in the 'ProgramData'-directory. I ran PoB directly from a folder on my Desktop. So I had no choice than to edit the manifest-file in that folder. This is what gave me the error at the time of bumping this thread.
> 
> After reading the reply from @Tomhet I did what I should have tried right away, but didn't, because reasons*.
> 
>     1. Removed the folder on my Desktop (but saved the Builds-folder).
> 
>     2. Downloaded the .exe-installation file from Openarl's github page.
> 
>     3. Installed it in the default path and did _not_ launch it after installation.
> 
>     4. The installation created the 'Path of Building'-folder in ProgramData with the manifest-file according to 'Layout 1' in the installation guide for this community fork. I copy-pasted the correct line of code from the guide. Saved and launched PoB.
> 
>     5. Success.
> 
> 
> * I avoided it since I didn't want to lose builds and shared custom items,

I just tried this and it failed the update at first but then I closed PoB to put my builds back in and when I opened it back up it worked. Guess it just takes a little fiddling around with, Thanks.

**Comment by LocalIdentity** [comment]
Should be fixed in 1.4.167.1. Please let me know if it does

**Comment by hofawd** [comment]
Fixed!   Thank you.
