### ISSUE TITLE
Having the support gems auto sort by dps on skills given by items

### ISSUE THREAD

**Issue by gabrielsubzero** [PathOfBuildingCommunity/PathOfBuilding#647]
Hello there! I had this issue when making builds around skills that are given by items, apparently the support gems don't sort when selecting the slot where the unique is (for example putting a group of gems in the Weapon 1 slot when wielding the Whispering Ice won't auto sort by dps).

This makes making building solely using those skills much harder to make, as i'm always unsure if my support gem selection is the most optimal or not.

**Comment by Jackalope-Gaming** [comment]
I'm glad I searched for this before making my own Issue.  This has always bugged me, but recently came up again as I'm trying to get Elemental Warding from Geofri's Baptism going.  When doing something like Ngamahu's Flame it's easy to slot Molten Strike instead since it's almost functionally identical, but certain unique skills don't really have a good way to kludge into working.
