### ISSUE TITLE
How is the Tattoo text separated?

### ISSUE THREAD

**Issue by CryAngel1970** [PathOfBuildingCommunity/PathOfBuilding#6577]
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

PoeCharm localizes PathOfBuildingCommunity for viewing in other languages.

I don't know the exact way it works, but
“English original text”, “Localized translation”
If you add it, the translated screen will be displayed.

For example, Korean
"(Disabled)","(사용안함)"
If you add something like this, it will be displayed in Korean.

However, the drop-down menu for the newly added Tattoo does not work.

"Honoured Tattoo of the Dove","비둘기의 명예로운 문신"

"Honored Tattoo of the Dove" and Are there any special characters in between "+4% to Chaos Resistance"?

Inserting a tab character doesn't work.

"Honoured Tattoo of the Dove +4% to Chaos Resistance","비둘기의 명예로운 문신 카오스 저항 +4%"

Slash doesn't work either.
"Honoured Tattoo of the Dove/+4% to Chaos Resistance","비둘기의 명예로운 문신/카오스 저항 +4%"

I contacted the PobCharm developer, and received a response telling me to ask the PoB developer what the text was like.

### Describe the solution you'd like

Please help me make it work by entering the following.
"Honoured Tattoo of the Dove","비둘기의 명예로운 문신"

### Additional context

![0028](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/b8afe1aa-93c8-411b-a714-0778c1258f6d)

**Comment by Wires77** [comment]
This same issue is present when using Timeless Jewels that replace nodes also.

What I'm guessing happens is on start-up PoeCharm replaces the `dn` values of nodes in the passive tree with the translated text.  However, for tattoos and timeless jewels the node information is stored in `Data/TattooPassives.lua` and `Data/TimelessJewelData/LegionPassives.lua`, respectively.  

@Chuanhsing is this accurate, and can it be updated to look in these locations for further translations?

**Comment by Chuanhsing** [comment]
PoeCharm uses the csv translation table and replaces the display layer. There is a problem that the strings on the screen cannot be translated normally:
"Honoured Tattoo of the Dove +4% to Chaos Resistance"
This string cannot be properly formatted because there may be \t or other special characters between "Honoured Tattoo of the Dove" and "+4% to Chaos Resistance".
If the special character is \t, the original translation string should be set to
  "Honoured Tattoo of the Dove\t+4% to Chaos Resistance"

**Comment by Wires77** [comment]
Oh I understand which text is causing the issue now.  It's a hack that was used for being able to search the dropdown for the actual stat given instead of just by tattoo/legion node name.

For tattoos the text is constructed like this:
```lua
label = node.dn .. "                                                " .. table.concat(node.sd, ","),
```
For Timeless jewel nodes:
```lua
label = node.dn .. "                                                " .. node.sd[1],
```
So for this specific situation, you'll want something like "Honoured Tattoo of the Dove                                                +4% to Chaos Resistance".  However, I'm not able to get that working in PoeCharm, but I've never used the program until now so it's possible I'm editing the wrong file or doing something else wrong.

We may end up coming up with a better solution than this in the future, so keep that in mind if it ever stops working.

**Comment by CryAngel1970** [comment]
The problem of node.sd having only 1 line was easily resolved.
![0030](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/6ecac3fc-191d-4434-a4b1-99af9222538d)

It does not work when node.sd has 2 or 3 lines.
![0031](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/8fb7ef71-53a6-429c-921a-31b4db4dff04)

look at TreeTab.lua, there seems to be a space between node.sd, but it doesn't seem to be working.
t_insert(descriptionsAndReminders, 1, node.sd[1] .. " " .. node.sd[2])


Thanks for your help.

**Comment by Wires77** [comment]
The dropdown uses the `label` property, you're looking at the `descriptions` property logic there.  For multiple lines, they are simply concatenated with a comma:
```lua
table.concat(node.sd, ",")
```
So just take each line and put a comma in between them.  For example, `Loyalty Tattoo of Utula                                                Trigger Summon Spirit of Utula Skill on taking a Savage Hit from a Unique Enemy,Limited to 1 Loyalty Tattoo`

Are you updating TreeTab.csv for this, by the way?  I tried doing that and restarting PoeCharm, but that didn't work.

**Comment by CryAngel1970** [comment]
It is successfully translated and printed.
Thank you again, Wires77.

![0032](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/583719/ce50a0ce-5d7f-40f7-af6a-00d8d8b7382d)
