### ISSUE TITLE
Tailwind does not increase Hit Rate of Brand skills

### ISSUE THREAD

**Issue by minlau** [PathOfBuildingCommunity/PathOfBuilding#683]
Cast Rate is increased, but Hit Rate is not. In result DPS is not increased.

Tried googling. Did not find a fully clear verification that Tailwind affects(or does not affect) Brand skills DPS, but I believe it should.

**Comment by minlau** [comment]
Just tested in game. Tailwind(Action speed) works hella weird. Cast speed modifier or casts per second or cast time or dps(on wave of conviction) does not change when you have Tailwind - so ingame cast rate does not match with pob.

**Comment by Quotae** [comment]
Brand skills say "Increases and Reductions to Cast Speed also apply to this skill's Activation frequency". Tailwind is not an increase or a reduction to cast speed, it's an action speed modifier. Action speed modifiers speed up the player's animations, which in turn does make you cast faster, but it's not a modifier to cast speed. Since it works by speeding up the player's animations, and Brand activation isn't tied to a player animation, Brands will not activate faster with Tailwind.
