### ISSUE TITLE
Incorrect base mana cost of Toxic Rain with Mirage Archer

### ISSUE THREAD

**Issue by archsmite** [PathOfBuildingCommunity/PathOfBuilding#7160]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

A Level 30 Toxic Rain has a base cost of 12 Mana in-game as well as listed on the skill gem. Mirage Archer does not affect the BASE mana cost.
![toxic rain](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51343261/58c83f60-23f0-473e-81f4-2969d78031e5)

### What is the value from the calculation in Path of Building?

POB states a level 30 Toxic Rain as having a base cost of 14 mana if it is high enough level and linked to Mirage Archer support.
![toxic rain 2](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/51343261/7cbb145c-f85b-4ffa-b29f-e1a52da9b9fd)

### How to reproduce the issue

1. Equip a bow with +1 socketed gems and +2 support gems
2. Add a level 21 Toxic Rain
3. Link Toxic Rain with Empower level 4 and Awakened Void Manipulation level 5
4. Observe that the base cost is correctly at 12 mana.
5. Link Toxic Rain with Mirage Archer Support
6. Base mana cost rises to 14 mana,

### Character build code

```shell
https://pobb.in/zrEI-bAy2ia_
```

**Comment by sida-wang** [comment]
Not enough time to get to the bottom of this yet but for any other devs:
Based on the debugger, by the time it gets to 
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Modules/CalcOffence.lua#L1548 
for some reason it thinks toxic rain is lvl 36 which is why the base mana cost is reflecting 14. 

![Screenshot 2023-12-25 160604](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/42928828/32fa6784-6e15-4b1f-8940-0dea50952b40)
