### ISSUE TITLE
В приложении не рассчитывается увеличение урона от молнии у предмета "Nebulis"

### ISSUE THREAD

**Issue by Quortimer** [PathOfBuildingCommunity/PathOfBuilding#7333]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the value from the calculation in-game?

В игре не проверял.

### What is the value from the calculation in Path of Building?

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/93127298/ea649ec2-9131-47b7-9a65-8baffcb25a39)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/93127298/1eecb0bf-17db-4979-bc59-cf6a73a0b6bf)

### How to reproduce the issue

1. Добавить Nebulis в PoB
2. Добавить предметы персонажу, что бы сопротивление молнии было свыше 75%.
3. Перейти во вкладку Calcs

### Character build code

```shell
https://pobb.in/DbwQMUHTThd2
```

**Comment by Regisle** [comment]
Not english so little hard to understand the issue, but from what I understand your assumption is that its total resistance above 75, 
> В игре не проверял.

maybe you should have tested it? as this is not how it behaves ingame, you have no resistance above 75, the 69 extra you have is "overcap" and does not apply to nebulis, you need to increase your maximum resistance, (eg via purity of lightning) to get a damage increase (otherwise nebulis would be the most broken item in the game giving tens of thousands of %damage)

hope this helps
