### ISSUE TITLE
Broken Herald reservation and it's interaction with Radiant Faith.

### ISSUE THREAD

**Issue by BuHoGPaD** [PathOfBuildingCommunity/PathOfBuilding#739]
https://pastebin.com/7JkXGMzY  - build.

Activating any auras increase ES correctly as long as I dont activate any heralds.
Activating Heralds boosts my ES in PoB much more that it really do in game. 
If I activate all and unspec Radiant Faith - numbers will be correct. So it's some weird interaction between this notable Ascendancy skill and reservation of heralds.

**Comment by TheVarkit** [comment]
For me activating ONLY discipline with radiant faith gives me the wrong ES value. Unspeccing Radiant Faith fixes the issue. https://pastebin.com/PZG6jYza

Ingame without Radiant Faith = 3707 ES
POB without Raidant Faith = 3707 ES

Ingame with Radiant Faith = 3767 ES
POB with Radiant Faith = 3827 ES

**Comment by rpm604** [comment]
I have an ES display bug that is similar to this. My ES total is around 1000 points HIGH in PoB.

With Discipline, and without, the PoB score is 1000 points too high. 2200ES in game vs 3250 in PoB without discipline, 6072 in game vs 7055 in PoB with discipline.

I have 777 reserved mana, which should provide me 77.7 raw ES from radiant faith. If I craft an item that adds 77 es, it adds approximately 220 ES total. Mousing over radiant faith displays 1200ES, so that's definitely the issue.

I have around +500% aura buff effect, so my guess is that PoB is still treating Radiant Faith like an aura from a skill, which it is not. :)

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
