### ISSUE TITLE
Adaptation to the game Last Epoch

### ISSUE THREAD

**Issue by Musholic** [PathOfBuildingCommunity/PathOfBuilding#7395]
Hello, I'm currently working on an adaptation of this tool to the game Last Epoch and I would like to make sure of a few things.

Having a tool like PoB for this game seems to be highly requested and I took the liberty to start a fork (https://github.com/Musholic/PathOfBuildingForLE). I hope someone else is not already working on something similar and one of the goals of this issue is to let others know about it. 

I would like to respect the work you already did so please tell me if I should mention anything particular in the Readme. I may name the tool "Path of Building for Last Epoch" but nothing is set in stone.

Regarding game data extraction, I'm not sure what I'm allowed to do/show. I know that the website "Last Epoch Tools" is already using game data extract and the devs seem fine about it. But I do have Python scripts in my repository which exposes the name of some game assets and hints about its contents.

If I'm allowed I may also mention which tool to use to extract the game data but I would be a bit surprised if I am.

Otherwise, I'm mainly focusing on features that can be automated from game extracts,  and I'm gradually removing irrelevant features. Any help regarding UI or rebranding changes would be appreciated :).

**Comment by Wires77** [comment]
You'll want to make sure to adhere to the licenses of our dependencies (https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/LICENSE.md) but the code license for PoB itself is pretty open.

A callout in the README would be nice, but not necessary, as people will see that you've forked this repo in Github itself.  There are enough changes you're going to have to make that it's basically going to be a new project anyway.

I'd recommend changing the icon from this repo: https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic
Otherwise anything UI-related is your choice.

I can't promise a lot of support, but if you'd like to drop into the Discord to chat off-topic, feel free to send me a PM @wires77.  Otherwise I wish you luck!

**Comment by Musholic** [comment]
Thank you, regarding the licenses I intend to also keep an MIT license. I just added it to the LICENSE.md file

I also added a special thanks in the Readme since I think you deserve it.

The icon will change at some point but it won't be my focus for now if you don't mind. But thanks for pointing where to change it.

Thanks for the support offer, I may ask you a few questions for things I have trouble to figure out :).
