### ISSUE TITLE
Constant errors while using spectral throw of materialization

### ISSUE THREAD

**Issue by Roo0s** [PathOfBuildingCommunity/PathOfBuilding#7465]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

Not cause constant error reports to pop up

### How does Path of Building behave?

When i use the gem vaal spectral throw of materialising i will get error popups randomly between 1 -2 mins.
Also there is no non-vaal version of the gem in pob.

### How to reproduce the issue

Put vaal spectral throw of materialising as your main skill materializingVaal

### Character build code

```shell
https://pobb.in/e8Kmrn4G4uCl
```

### Screenshots

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/73453232/e0c3da98-ffc9-4998-9659-35fe063001c9)

**Comment by Ciccooz** [comment]
Seems to happen when you hover specific items from here: 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/43402870/6bfad50f-0370-439c-b88a-09e2ac7507f0)

This are the following items that lead to an error:
**Uniques:** 
- Agnerod East
- Agnerod North
- Agnerod South
- Agnerod West
- Atziri's Spledour
- Cold Iron Point
- The Consuming Dark
- Maata's Teaching
- Replica Cold Iron Point
- Replica Dragonfang's Flight
- Taryn's Shiver
- Xirgil's Crank

**Rares:**
- All +5 rares

I'll try to give a look at the code to understand why is happening.
In the meantime the only suggestion i can give you is to avoid this items if you can, since the error is annoying.
