### ISSUE TITLE
The Green Nightmare dodge and frenzy gain affixes not recognized

### ISSUE THREAD

**Issue by oseparovic** [PathOfBuildingCommunity/PathOfBuilding#769]
The bottom two affixes of The Green Nightmare do not seem to have any impact in PoB.

- Passives granting Cold Resistance or all Elemental Resistances in Radius also grant Chance to Dodge Attack Hits at 35% of its value
- Passives granting Cold Resistance or all Elemental Resistances in Radius also grant equal chance to gain frenzy charge on kill

**Expected**:
![image](https://user-images.githubusercontent.com/3710226/79134152-14f3a400-7d62-11ea-81a5-35d32e9c9640.png)

**Actual**:
![image](https://user-images.githubusercontent.com/3710226/79134188-263cb080-7d62-11ea-8ea6-7c76819c26ed.png)

**Comment by ppoelzl** [comment]
The item text got reworded in game. This will be fixed in the next update.
Right now, you can just grab a "The Green Nightmare" from PoB instead and it will work correctly.

"Chance to gain a Frenzy Charge on Kill" doesn't do anything, as PoB can't know what you're killing or not killing. This in intended, and working correctly. You can manually set your Frenzy Charges in the Config tab instead.

**Comment by oseparovic** [comment]
Confirmed!

![image](https://user-images.githubusercontent.com/3710226/79135655-8df3fb00-7d64-11ea-8e55-6cf67a532a8c.png)

Thanks for the super quick reply

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
