### ISSUE TITLE
Unable to update due to MSVCR100.dll missing

### ISSUE THREAD

**Issue by TactfulRanger** [PathOfBuildingCommunity/PathOfBuilding#7744]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

Whenever I'm updating through Path of Building, the following error pops up:

![image](https://github.com/user-attachments/assets/66e4225a-84e2-44a4-aa18-c0f88e5019df)

Cancelling the update progress.

### How does Path of Building behave?

Unable to update

**Comment by TactfulRanger** [comment]
Okay I just managed to resolve this by installing the x86 version of:

https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe

The x64 doesn't fix it... but should this come installed with Path of Building to prevent such errors?

**Comment by zao** [comment]
The update helper EXE indeed needs `MSVCR100.dll` to run. We don't ship it with the project for historical reasons before my time with the project. Most users don't notice as that VC++ runtime ships in most OS installations and is commonly installed by other programs, masking the problem.

As you've noticed, installing the runtime system-wide addresses the problem. The redist we used is available inside the `runtime-win32.zip` file from the repository. You could also obtain the DLL file separately and put it directly in the PoB directory for a "private deployment" to avoid having to modify your system, something which might be relevant if you use the portable installation on a borrowed computer.

Due to how the update system was built, we can't actually update the update helper itself and its direct dependencies as it then attempts to update those files while they're in use and gets stuck. 🤪

**Comment by SimplePotential** [comment]
Confirming this does fix the problem.  I had it as well and fixed it, might be worth mentioning it in the readme.

**Comment by zao** [comment]
Taking a look at things, it turns out that the portable installation already bundles the file so this problem should be limited to the regular installer.

Taking a look at the installer, it seems that we removed the runtime DLL when adding the new SimpleGraphic 2.0 renderer back in https://github.com/PathOfBuildingCommunity/PathOfBuilding-Installer/commit/49b94706abef7fd9501184fa31c9843a23e030b3. We should probably fix that, thanks to all making us look into this.

**Comment by gojlus** [comment]
Hey also experiencing this issue, after addressing the .dll missing, I instead got issues involving "unable to start correctly 0xc000007b" 

The only thing I could find issue with is UPDATE.EXE being on x86 architecture instead of x64?

pics for reference
dependency walker of the update.exe 
![update](https://github.com/user-attachments/assets/88ea3aeb-a6f4-4580-8c02-b7c5229643c6)
dependency walker of PoB.exe
![PoB](https://github.com/user-attachments/assets/53891642-768c-4fae-b768-449a0d59b816)

**Comment by Wires77** [comment]
I've fixed this issue in the installer in the next release.  In the meantime, you should be able to find the DLL @zao mentioned in the runtime-win32.zip folder if you're missing it.

@gojlus Your issue sounds separate from the others'  Have you tried reinstalling PoB or using the portable version?

**Comment by gojlus** [comment]
@Wires77  I've tried uninstalling + reinstalling from https://pathofbuilding.community/ 
I don't know what the portable version is. 

I thought my issue was similar since I initially had the same problem of missing MSVCR100.dll, but fixing that problem caused my current one. -- I've tried reinstalling+installing vc++ redist. for x64/86 for 2010/2012/2013/2015-2022, and downloaded .net framework 3.5.

**Comment by Wires77** [comment]
The portable version is here: https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.45.0/PathOfBuildingCommunity-Portable.zip You'll just run PoB from that folder instead of your normal one.  What kind of computer are you running and what version of Windows?

**Comment by gojlus** [comment]
I semi-recently build a new pc. 

running windows 10 home, Version 10.0.19045 Build 19045

Device name	DESKTOP-VG88DU7
Processor	AMD Ryzen 5 7600 6-Core Processor                 3.80 GHz
Installed RAM	32.0 GB (31.1 GB usable)
Device ID	34B4A66F-5A37-44D7-959B-E7A90AC477B0
Product ID	00325-80000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

-------------------------------------------------------------------------------

I installed the portable version, and update.exe no longer brings up the "application error: unable to start correctly 0xc00007be" when using that folders Update.exe, it instead brings up a command prompt with no input file specified. I think that's correct behavior even though it's presenting the same as it did previously in Dependancy-walker with the mismatched cpu error.

**Comment by Wires77** [comment]
Alright, that sounds like a good sign.  You may be able to replace your non-functional Update.exe with this new one, but you also may have to wait until another update comes out to ensure everything works.  Let me know if it breaks again when v2.46.0 comes out

**Comment by gojlus** [comment]
Will do, and Thank you so much for pointing me in the right direction. <3

**Comment by BenzoBernd** [comment]
Also got the MSVCR100.dll error on updating.
Fresh install of Win10 but the portable version works fine.
Would be great to at least mention which Microsoft Visual C++ Version you need for the non portable version run/update.

**Comment by Wires77** [comment]
@BenzoBernd can you try reinstalling?  I just updated the installer to include that file in the last release, want to make sure people aren't still having issues
