### ISSUE TITLE
Cant load Cluster "tree"

### ISSUE THREAD

**Issue by Unrealchicken25** [PathOfBuildingCommunity/PathOfBuilding#787]
Hello ! 

My cluster jewel are loaded into my tree but i can't access their tree :
![image](https://user-images.githubusercontent.com/35172316/79361130-2fd23e00-7f45-11ea-977f-aab9c4d5d19b.png)

it only happend on this character

**Comment by heyfunny** [comment]
I am also having this issue with 1 of my cluster jewels a large 8 node one I believe its because GGG changed the bow cluster jewel to include damage over time in one of the recent patches since that is the line on the jewel description that is in red.  Did GGG change anything about that line in your jewel as well in a patch?

**Comment by LocalIdentity** [comment]
This is fixed in the next update, which should be out in the next 24 hours as long as there are no bugs discovered

**Comment by LocalIdentity** [comment]
For now, you will have to manually create the jewel in the item crafter

**Comment by LocalIdentity** [comment]
Fixed in 1.4.169.1
