### ISSUE TITLE
Multistrike will work with shield charge in 3.25 according to patch note

### ISSUE THREAD

**Issue by sanctify** [PathOfBuildingCommunity/PathOfBuilding#7945]
### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### Is your feature request related to a problem?

Simply a 3.25 feature/change you could have missed. Maybe you're already working on this :)

### Describe the solution you'd like

Make the multistrike gem able to support shield charge

### Describe alternatives you've considered

I use custom modifiers but i'm not sure of the precision atm

### Additional context

![image](https://github.com/user-attachments/assets/f96d267c-81c0-4929-aa92-9ebae6c83d6c)

**Comment by deathbeam** [comment]
From patch notes:

Multistrike Support and Awakened Multistrike Support now describe that they cannot support Travel Skills, rather than every Travel Skill stating they cannot be supported by Multistrike. They also now describe that they cannot support Retailation Skills.

Now its mentioned on multistrike itself instead of gem

**Comment by sanctify** [comment]
My bad, sorry for the inconvenience and thanks again !
