### ISSUE TITLE
infinity result in effective hit pool calculation

### ISSUE THREAD

**Issue by DracheTek** [PathOfBuildingCommunity/PathOfBuilding#7976]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

When armor reach a certain threshold, the calculation of "effective hit pool" would have "infinite" result.

### How does Path of Building behave?

Checked the step by step calculation, the mitigated damage is around 300, the mitigate rate(come from block) is around 40%, the result should be around 60000.

### How to reproduce the issue

create build from the following link and the problem should reproduce itself

### Character build code

```shell
https://pobb.in/__4B0EuMlCjk
```

**Comment by Regisle** [comment]
If you disable gain on block the calcs seem correct
4247 pool, 390.33 taken = 10.88 hits before death (same as PoB), 43% unmitigated after block 10.88/0.43 = 25.30 (close to PoBs 25.3, error due to rounding)

with es on block you are taking 167.8419 damage on average and gaining 239 es and 41 life, so you will never die
either disable gain on block or actually configure the enemy to do a proper amount of damage (eg even setting it to a boss, even with aegis you only have 20k ehp, let alone vs a much higher hit)
