### ISSUE TITLE
PoB calculating 101%+ spell suppression chance as 30k lower EHP as 100% spell suppression chance

### ISSUE THREAD

**Issue by Reino-X** [PathOfBuildingCommunity/PathOfBuilding#8088]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

When I get beyond 100% (101+%) spell. sup. chance it shouldnt reflect it as a negative on my EHP.

### What is the value from the calculation in Path of Building?

what happens is I go from 160k ehp to 105k ehp

### How to reproduce the issue

select ''reflexes in the passive tree'' and it will go lower ehp

### Character build code

```shell
https://pobb.in/f3Q6HmdndLgM
```

### Screenshots

![image](https://github.com/user-attachments/assets/347c9500-9da7-47bf-bb19-7ba15b737ced)
![image](https://github.com/user-attachments/assets/68e7f31c-a6ea-40ea-bf36-d6bb8e63a326)

**Comment by Regisle** [comment]
An interesting issue, its because PoB is no longer gaining es when you suppress during the ehp calcs, as your mitigation is the same when those calcs are run, if you have 1% block, spell block, avoidance or dodge chance itll calc that again

Either way the reason the change is so big is because you have the enemy configured to do almost no damage (default of a white mob), if you set the enemy to a boss the difference is only a 1.5% loss, and if you set it to a guardian it goes back to increasing it as the tiny amount of es on spell suppress has almost no effect on how many hits you can survive

Ill see about fixing this at some point

**Comment by Reino-X** [comment]
idk, I have configured the mobs to be lvl 85. I described the title how I had problems with it. the 30k ehp loss didnt appear otherwise. thank you very much regardless.

**Comment by Reino-X** [comment]
Also for your edit. I dont want or need more than 100% suppress chance, but if I would invest in passives up to ''reflexes'' it couldnt be helped that there would be a little bit of a cap breach. and it dosent lower it by 99%, but by around 53k ehp which is around 30% of it (it wasnt 30k, I just checked)
