### ISSUE TITLE
Veteran's Awareness not working with Steelskin

### ISSUE THREAD

**Issue by Vulcaiiin** [PathOfBuildingCommunity/PathOfBuilding#834]
When allocating the node from the unique small jewel "The Front Line" that grants the notable Veteran's Awareness, it does not work with the guard skill "Steelskin".
It works well with Molten Shell but doesn't work for Steelskin, and I think it should as it is also a Guard Skill.

**Comment by Lothrik** [comment]
Arcane Cloak doesn't work with Veteran's Awareness either, as it seems to be missing from ModParser and ModCache.

Adding Arcane Cloak to those two files seems to fix that, but Steelskin is a bit more complicated and I'm not entirely sure why (it has no buff implemented and it's referred to as QuickGuard instead of Steelskin in several places).

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.19.
