### ISSUE TITLE
Elemental Hit melee not supported by AoE Gems

### ISSUE THREAD

**Issue by banang** [PathOfBuildingCommunity/PathOfBuilding#856]
heya, I've been messing around with elemental hit and noticed that in the 1.4.169.2 version of your great tool, Elemental Hit is not fully functional with Support Gems that modify AoE.

For example Pulverise Support will correctly lower the attack speed, however it does not increase damage.

my build: https://pastebin.com/766U5UdT

**Comment by Quotae** [comment]
It doesn't change the damage because Elemental Hit has two separate parts that do not hit the same enemy. The part that is displayed in PoB is the initial hit, which doesn't deal AoE damage. Pulverise Support can support any melee attack skill, not just melee area attacks, so that's working as intended as well.

It would be relatively easy to add a new skill part that displays the AoE DPS, but that's not really that useful unless you're trying to optimize the AoE's damage for clear, and even then your options are pretty limited(you're pretty much just going to link it to Pulverise and Increased Area of Effect and you don't have a lot of options). It would also add quite a bit of bloat since Elemental Hit already has three skill parts.

Also I'm personally not sure if the AoE damage on Elemental Hit is considered Melee area damage, which would affect whether its damage is actually affected by Pulverise or not. Someone else might know this, though.

**Comment by banang** [comment]
ahh i see! 
i completely understand you developers have tons of work to do (and for free, on top of it all) and cannot spare some time to add a feature that so far, nobody seems to have missed.

thanks for clearing it up!
