### ISSUE TITLE
Chaos DOT Multiplier Missing from Calculations for Poison

### ISSUE THREAD

**Issue by captainzmaster** [PathOfBuildingCommunity/PathOfBuilding#857]
I was trying to figure out how chaos dot multiplier affected my poison dps, when I noticed that I couldn't find the dot multiplier in any of the calculations.

To reproduce, add a skill with poison damage and take chaos dot multi on the tree or jewel. You will not be able to find the multi in the poison calculations.

POB still shows that removing a jewel with only chaos dot multi on it will reduce your poison dps, so I think the problem is just that it is not being shown in the Calcs tab.

Example Build with bug: https://pastebin.com/8f330621

**Comment by wolfie-poe** [comment]
This bug prevails in the latest patch (1.4.170.6 @ 2020/07/22). It seems to be a display bug.

**Comment by Quotae** [comment]
Yep, purely a display bug. You can see in the breakdown itself that it's still counting the DoT multi:
![image](https://user-images.githubusercontent.com/39030429/88138392-33640980-cbb3-11ea-89d4-d4ddbf4f4d85.png)

I'm the one that added the DoT multi breakdowns to this update, and when I was writing the breakdown there I accidentally wrote "PoisonDotMultiplier" instead of "ChaosDotMultiplier", which is what's correct. Damage is still being calculated correctly, it's just that that tooltip just isn't showing sources of Chaos DoT Multiplier in the list. Fixed in PR #1255, which should come in an update sometime in the not-too-distant future.

**Comment by LocalIdentity** [comment]
Fixed in 1.41.170.7
