### ISSUE TITLE
Feature request: Configuration checkboxes for more non-damaging elemental ailments

### ISSUE THREAD

**Issue by SabreCat** [PathOfBuildingCommunity/PathOfBuilding#889]
**Is your feature request related to a problem? Please describe.**

I've been tinkering with the cluster jewel "The Interrogation" and its associated notable passive, "Secrets of Suffering". In particular, using it with non-player-originating sources of ignite/shock/chill to stack as many different elemental ailments at a time as possible, and thus crank up the benefit from Elemental Hit's `10% more Damage per Elemental Ailment on the Enemy` effect.

(Yes, it's a jank offmeta build. That's my jam, haha.)

However, I can't find any option to apply the alternative elemental ailments "Scorch, Brittle, and Sapped" to see their effects on the damage output.

**Describe the solution you'd like**

Add 

- Is the enemy Scorched?
- Is the enemy Brittle?
- Is the enemy Sapped?

to the "For Effective DPS" section of the Configuration screen.

These could also have an "Effect of ___" spinner like Shock does, given that the effects have a similar graded scheme, which could in turn calculate the effects (e.g. crit chance for Brittle) of a given ailment amount.

**Describe alternatives you've considered**

I can eyeball it by checking how much toggling "Is the enemy Ignited?" adds, and manually calculating what further similar boosts to Elemental Hit would accomplish.

**Additional context**

![image](https://user-images.githubusercontent.com/4501321/81488913-0e5b2e00-9235-11ea-8754-e5a0e7427b9a.png)

![image](https://user-images.githubusercontent.com/4501321/81488918-1a46f000-9235-11ea-9135-5347341aed04.png)

![image](https://user-images.githubusercontent.com/4501321/81488921-2468ee80-9235-11ea-8d02-4232b222aff6.png)

**Comment by Quotae** [comment]
Done! PR up here: #891 

After review, it should eventually be merged. For now, if you want to more accurately simulate the ailments on your build, here's more specifics.

- Add "23% more Damage" to an item or jewel if you're using six ailments (This will simulate having either Ignite or Freeze, Chill, and Shock with Scorch, Brittle, and Sap as well. 60% more / 30% more = ~23% more damage)
- Add "21% more Damage" if you're using all 7 ailments
- Add "25% more Damage" if you're using 5 ailments (Chill, Shock, Scorch, Brittle, and Sap)
- Add 15% to the value of Shock in the config screen if you're using Yoke of Suffering(or just add 5% for each extra ailment you'd have)
- Add "+x% to Critical Strike Chance" to an item or jewel where x is the extra crit chance from the effect of Brittle
- Change the boxes in Config for each elemental resistance for the effect of Scorch

Though the last 2 are kind of iffy since we have no idea how easy it is to apply big values of Scorch and Brittle.

**Comment by Ydoum** [comment]
when can we expect this to be patched into the live client?

**Comment by ppoelzl** [comment]
Next update.

**Comment by Ydoum** [comment]
@ppoelzl awesome, thank you <3

**Comment by LocalIdentity** [comment]
Fixed in 1.4.170.1
