### ISSUE TITLE
PoB not launching

### ISSUE THREAD

**Issue by VeldoraTempest** [PathOfBuildingCommunity/PathOfBuilding#994]
Using the latest communtiy fork.

* **What happened?** After fresh installing the latest PoB, clicking the Path of building.exe file brings cmd screen showing press any key to continue. PoB not launching at all.
* **What were you trying to do?** I did fresh install PoB fork,
* **What steps will reproduce the bug?** No matter how many times I reinstall the PoB it is showing cmd window with the same message.
* **Does it reproduce every time? If not, why so?** Yes everytime. Only time PoB launches successfully when I luanch it from the shortcut created by the checkbox which is showed after reinstalling the PoB. But creating a desktop shortcut of the Path of Building.exe from the installation folder doesn't work. 
* **Additional information:** Nothing special.

**Comment by Wiirlak** [comment]
Same problem here, exact same scenario.

**Comment by LocalIdentity** [comment]
Have you tried using the new 1.4.169.3 installer released today?

**Comment by Wiirlak** [comment]
Yes I did, same result

**Comment by ppoelzl** [comment]
Where did you install it to?

**Comment by VeldoraTempest** [comment]
Only workaround for it now is to use the zip file. Installing doesn't work.

**Comment by Wiirlak** [comment]
Thanks you for the workaround, it works with the zip !

**Comment by sweigle333** [comment]
Just to provide some more details, I attempted to install it to both My Documents and Program Files (x86). The installer attempts to install it automatically to Program Files (x86); however, I think I had previously had the Openarl PoB installed to My Documents, as that is where my previous builds were located. In both instances, the cmd.exe window opened rather than PoB.

**Comment by ppoelzl** [comment]
Fixed in 1.4.170.4.
